[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fragalyseqt"
version = "0.5.2"
dependencies = [
    "pyqtgraph >= 0.11.0",
    "biopython >= 1.58",
    "scipy >= 1.5.0",
    "charset-normalizer",
    "platformdirs >= 2.0",
]
requires-python = ">=3.8"
authors = [
    {name = "Alexandr Dorif", email = "dorif11@gmail.com"},
]
description = "Tool for DNA fragment analysis data handling."
readme = "README.md"
license = "AGPL-3.0-only"
keywords = ["fragalyseqt", "biology", "DNA", "MLPA", "QF-PCR", "FSA", "ABIF", "STR", "HID", "TP-PCR"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Topic :: Education",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Natural Language :: English",
    "Natural Language :: Russian",
    "Natural Language :: Ukrainian",
    "Natural Language :: Romanian",
    "Natural Language :: French",
    "Natural Language :: Bulgarian",
    "Natural Language :: German",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
Homepage = "https://github.com/Dorif/fragalyseqt"
Documentation = "https://github.com/Dorif/fragalyseqt/blob/master/README.md"
"Bug Tracker" = "https://github.com/Dorif/fragalyseqt/issues"

[project.gui-scripts]
fragalyseqt = "fragalyseqt.main:main"

[tool.setuptools.package-data]
fragalyseqt = ["*.xml", "*.wsdl"]

[tool.pytest.ini_options]
testpaths = ["tests"]
