#!/usr/bin/env python3
"""Generate the PyPI long description without changing the offline README."""

import argparse
from pathlib import Path
import re
from typing import Tuple

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "README.md"
TARGET = ROOT / "README.pypi.md"
INIT = ROOT / "src" / "fragalyseqt" / "__init__.py"
REPOSITORY = "https://raw.githubusercontent.com/Dorif/fragalyseqt"


def project_version() -> str:
    text = INIT.read_text(encoding="utf-8")
    match = re.search(r'^__version__ = "([^"]+)"$', text, re.MULTILINE)
    if not match:
        raise RuntimeError(f"Cannot find __version__ in {INIT}")
    return match.group(1)


def render() -> Tuple[str, str]:
    version = project_version()
    base_url = f"{REPOSITORY}/v{version}"
    text = SOURCE.read_text(encoding="utf-8")

    images = (
        "FragalyseQt.png",
        "FragalyseQt_current_interface.png",
    )
    for image in images:
        local = f'src="{image}"'
        remote = f'src="{base_url}/{image}"'
        if local not in text:
            raise RuntimeError(f"Expected image reference not found: {local}")
        text = text.replace(local, remote, 1)

    local_releasing = "[RELEASING.md](RELEASING.md)"
    if local_releasing not in text:
        raise RuntimeError(f"Expected documentation link not found: {local_releasing}")
    text = text.replace(
        local_releasing,
        f"[RELEASING.md](https://github.com/Dorif/fragalyseqt/blob/v{version}/RELEASING.md)",
        1,
    )

    generated = (
        "<!-- Generated by scripts/prepare_pypi_readme.py; do not edit. -->\n\n"
        + text
    )
    return version, generated


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if README.pypi.md is not up to date",
    )
    args = parser.parse_args()
    version, generated = render()

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != generated:
            raise SystemExit(
                "README.pypi.md is stale; run scripts/prepare_pypi_readme.py"
            )
        print(f"{TARGET.relative_to(ROOT)} is current for v{version}")
        return

    TARGET.write_text(generated, encoding="utf-8")
    print(f"Generated {TARGET.relative_to(ROOT)} for v{version}")


if __name__ == "__main__":
    main()
