# This file is part of FragalyseQt.
#
# FragalyseQt is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# FragalyseQt is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with FragalyseQt. If not, see <https://www.gnu.org/licenses/>.

def localizefq(iface):
    from os import name, getenv
    if name == 'posix':
        lang = getenv('LANG')
    elif name == 'nt':
        from locale import windows_locale
        from ctypes import windll
        lang = windows_locale[windll.kernel32.GetUserDefaultUILanguage()]
    else:
        lang = "en"
    lang = lang.lower() if lang else None
# Some systems may have C or POSIX locale or no locale set. The codeset is
# stripped first, so every spelling of the neutral locale ("C", "C.UTF-8",
# "C.utf8", "POSIX") is recognised. The comparison is exact: "c" is not a
# language code, and a substring test would swallow real locales containing
# that letter (e.g. "cs_CZ", "zh_CN").
    neutral = lang.split(".")[0] if lang else None
    supported = ("en", "ru", "ua", "ro", "fr", "bg", "de", "zh")
    if lang is not None and neutral not in ("c", "posix") and not any(
            token in lang for token in supported):
# An unsupported locale (e.g. es_ES, ja_JP) has no block below, which would
# leave `iface` empty and turn every later lookup into a KeyError. Fall back
# to English instead of starting the application with no interface strings.
        lang = "en"
        neutral = "en"
    if lang is None or neutral in ("c", "posix") or any(
            token in lang for token in ("en", "c.utf-8", "posix")):
        iface['ch_inact_msg'] = "Inactive channel"
        iface['aboutbtn'] = "About"
        iface['infoboxtxt'] = "FragalyseQt version 0.5.4, codename \"Southern"\
                              "\".\n\nThis program version supports "\
                              "analysis of up to 8 different fluorescense "\
                              "channels simultaneously, selective channel "\
                              "hiding, non-Latin run names and can correctly"\
                              " handle damaged files, exporting peaks "\
                              "locations, areas, sizes, FWHM's and channel "\
                              "names in CSV for any *.FSA/*.HID files and "\
                              "export in CSV internal analysis data for "\
                              "*.FSA/*.HID files generated by ABI 3500 and "\
                              "SeqStudio series equipment. Also supports "\
                              "reading native Nanophore-05 .frf files "\
                              "(highly experimental). Since version 0.5, "\
                              "allele binning using GeneMapper, GeneMarker"\
                              " and NCBI OSIRIS LadderInfo panel files is"\
                              " supported. When a panel with stutter ratio"\
                              " data is loaded (GeneMapper Stutter files or"\
                              " GeneMarker panels), stutter peak filtering is"\
                              " applied automatically. Note: NCBI OSIRIS"\
                              " panels do not carry stutter ratio data —"\
                              " stutter filtering is not available for them."\
                              " Export to CODIS 3.2 CMF XML format is also "\
                              "supported (Ctrl+Shift+C): select samples, "\
                              "assign specimen categories and lab metadata, "\
                              "and FragalyseQt will generate a schema-valid"\
                              " CODISImportFile ready for submission.\n\n"\
                              "Peaks areas are calculated assuming they are "\
                              "Gaussian.\n\nGNU AGPL version 3 licensed.\n\n"\
                              "If you wish to contact the author for any"\
                              " reason - please write at dorif11@gmail.com"
        iface['openfragmentfile'] = "Open file"
        iface['exportinternal'] = "Export Internal Analysis Data"
        iface['csvexport'] = "Export in CSV"
        iface['exportwholesession'] = "Export whole session"
        iface['choosefolder'] = "Choose export folder"
        iface['unsuppeq'] = "Unsupported equipment!"
        iface['unsuppeqmsg'] = "Internal analysis data could be exported only"\
                               " from FSA files generated by ABI 3500 and "\
                               "SeqStudio family sequencers!"
        iface['dmgdfile'] = "Damaged file!"
        iface['nodatamsg'] = "There are no data in file!"
        iface['hidechannel'] = "Hide "
        iface['minph'] = "Select minimal peak height:"
        iface['minpw'] = "Select minimal peak width:"
        iface['minpp'] = "Select minimal peak prominence:"
        iface['minww'] = "Smoothing window half-width:"
        iface['minpkwl'] = "Detection window width:"
        iface['minah'] = "Min. allele height:"
        iface['minah_homo'] = "Min. homozygote height:"
        iface['minah_homo'] = "Min. homozygote height:"
        iface['menu_view'] = "View"
        iface['splitview'] = "Split channels"
        iface['savecsv'] = "Save CSV"
        iface['bcd'] = "Baseline correction and denoising."
        iface['processbatch'] = "Process whole batch"
        iface['savesession'] = "Save Session"
        iface['opensession'] = "Open Session"
        iface['savesessiontitle'] = "Save Session"
        iface['opensessiontitle'] = "Open Session"
        iface['sessionnamelabel'] = "Session name:"
        iface['sessionverifytitle'] = "File Verification"
        iface['sessionverifymsg'] = "One or more source files are missing or "\
                                    "have been modified.\nThe session will "\
                                    "open in read-only mode using data "\
                                    "stored in the database."
        iface['openreadonly'] = "Open read-only"
        iface['nosessions'] = "No saved sessions found."
        iface['readonlyplot'] = "Read-only — source file unavailable"
        iface['wrongsizing'] = "Wrong ladder or sizing method! Please, try "\
                               "another ones!"
        iface['closetab'] = "Close Tab"
        iface['loadpanel'] = "Load Panel"
        iface['nopanel'] = "No panel loaded"
        iface['allele_col'] = "Allele"
        iface['loadpaneldlg'] = "Load panel file"
        iface['loadbinsdlg'] = "Select companion bins file"
        iface['nobinsmsg'] = "No bins file was found or selected. "\
                             "Only marker ranges will be used for "\
                             "annotation — specific allele numbers "\
                             "will not be available."
        iface['loadstutterdlg'] = "Select stutter ratios file"
        iface['codisexport'] = "Export CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['freq_tables_menu'] = "Frequency Tables"
        iface['ref_profiles_menu'] = "Reference Profiles"
        iface['importfreqtable'] = "Import Frequency Table"
        iface['importpanel'] = "Import Panel to Library"
        iface['panelimported'] = "Panel(s) saved to library."
        iface['codisdlgtitle'] = "CODIS 3.2 CMF Export"
        iface['codisdestori'] = "Destination ORI:"
        iface['codissourcelab'] = "Source Lab ID:"
        iface['codisanalyst'] = "Submit User ID:"
        iface['codisbatch'] = "Batch ID (optional):"
        iface['codiskit'] = "Kit (optional):"
        iface['codisdt'] = "Submit date/time:"
        iface['codisspecimens'] = "Specimens:"
        iface['codisfile'] = "File"
        iface['codisspecimenid'] = "Specimen ID"
        iface['codiscategory'] = "Category"
        iface['codiscmftitle'] = "CODIS CMF Export"
        iface['codisformat'] = "Format:"
        iface['codismsgid'] = "Message ID:"
        iface['codisinstrid'] = "Instrument ID:"
        iface['codismanuf'] = "Manufacturer:"
        iface['codismodel'] = "Model:"
        iface['codissoftver'] = "Software version:"
        iface['codisuniqueevent'] = "Unique Event ID"
        iface['codisfingerprintdt'] = "Fingerprint date/time"
        iface['codisarrestoffense'] = "Arrest offense"
        iface['codisrapidvalidation'] = "Rapid Import requires Destination "\
                                        "ORI, Source ORI, Message Creator "\
                                        "User ID, Message date/time, Message "\
                                        "ID and Instrument ID, plus per "\
                                        "specimen: Unique Event ID, "\
                                        "Fingerprint date/time and Arrest "\
                                        "offense."

        iface['codisnopanel'] = "\u26a0 Some tabs have no panel loaded — "\
                                "locus data will be absent for those specimens."
        iface['codisnosize'] = "\u26a0 Some tabs have no sized peaks — "\
                               "locus data will be absent for those specimens."
        iface['codisvalidation'] = "Please fill in: Destination ORI, Source "\
                                   "Lab ID, Submit User ID and date/time."
        iface['codisemptyid'] = "Specimen ID is empty for a selected row."
        iface['codisnorows'] = "No specimens selected for export."
        iface['codissave'] = "Save CODIS XML"
        iface['menu_file'] = "File"
        iface['menu_settings'] = "Settings"
        iface['menu_help'] = "Help"
        iface['addsizestd'] = "Add size standard"
        iface['stdname'] = "Standard Name:"
        iface['stdchannel'] = "ILS Channel (ABIF key):"
        iface['stdsizes'] = "Sizes (space separated):"
        iface['stdadded'] = "Size standard added successfully"
        iface['stdimportxml'] = "Import from file"
        iface['stdimporterr'] = "Could not parse size standard from file."
        iface['menu_analysis'] = "Analysis"
        iface['compare_profiles'] = "Compare Profiles"
        iface['search_profile'] = "Search in Database"
        iface['search_profile_dlg'] = "Search Profile in Database"
        iface['search_profile_no_match'] = "No matching profiles found."
        iface['search_profile_exact'] = "Exact match"
        iface['search_profile_partial'] = "Partial match"
        iface['search_profile_col_name'] = "Name"
        iface['search_profile_col_role'] = "Role"
        iface['search_profile_col_match'] = "Matched / Common"
        iface['search_profile_col_status'] = "Status"
        iface['search_profile_query'] = "Query profile:"
        iface['search_profile_nothing_to_search'] = "There are no saved profiles to search with. Open a file or save a profile first."
        iface['save_profile'] = "Save Profile to Database"
        iface['save_profile_dlg'] = "Save Profile"
        iface['save_profile_name'] = "Name:"
        iface['save_profile_role'] = "Role:"
        iface['save_profile_notes'] = "Notes (optional):"
        iface['save_profile_saved'] = "Profile saved to database."
        iface['save_profile_empty'] = "No allele calls found. Load a panel and run analysis first."
        iface['save_profile_db'] = "Database:"
        iface['save_profile_db_casework'] = "Casework"
        iface['save_profile_db_refprofiles'] = "Reference profiles"
        iface['cmp_title'] = "Profile Comparison"
        iface['cmp_prof1'] = "Profile 1:"
        iface['cmp_prof2'] = "Profile 2:"
        iface['cmp_freqtable'] = "Frequency table:"
        iface['cmp_import_csv'] = "Import CSV."
        iface['cmp_theta'] = "θ (FST):"
        iface['cmp_identity'] = "Identity"
        iface['cmp_kinship'] = "Kinship"
        iface['cmp_relationship'] = "Relationship:"
        iface['cmp_calculate'] = "Calculate"
        iface['cmp_no_table'] = "No frequency table loaded. Import a CSV first."
        iface['cmp_no_tabs'] = "Open at least 2 files to compare."
        iface['cmp_nothing_to_compare'] = "Nothing to compare yet. Open "\
                                          "files or save at least 2 "\
                                          "profiles to the reference "\
                                          "database."
        iface['cmp_combined_lr'] = "Combined LR:"
        iface['cmp_log10_lr'] = "log₁₀ LR:"
        iface['cmp_conclusion'] = "Conclusion:"
        iface['cmp_loci_stat'] = "Loci typed: {n}   Excluded: {m}"
        iface['cmp_only_in_1'] = "Only in Profile 1:"
        iface['cmp_only_in_2'] = "Only in Profile 2:"
        iface['cmp_contradicting'] = "Contradicting loci: {n}"
        iface['cmp_export_pdf'] = "Export PDF"
        iface['cmp_save_pdf'] = "Save comparison PDF"
        iface['cmp_export_pdf'] = "Export PDF"
        iface['cmp_save_pdf'] = "Salvați raportul PDF"
        iface['cmp_export_csv'] = "Export CSV"
        iface['cmp_save_csv'] = "Save comparison CSV"
        iface['cmp_import_codis'] = "Import CODIS XML."
        iface['cmp_codis_imported'] = "{n} profile(s) imported."
    elif "ru" in lang:
        iface['ch_inact_msg'] = "Неактивный канал"
        iface['aboutbtn'] = "О программе"
        iface['infoboxtxt'] = "FragalyseQt версия 0.5.4, кодовое имя "\
                              "\"Саузерн\".\n\nЭта версия программы "\
                              "поддерживает одновременный анализ до 8 каналов"\
                              " флуоресценции, избирательное сокрытие каналов"\
                              ", не-латинские имена запусков, может правильно"\
                              " работать с повреждёнными файлами, "\
                              "поддерживает экспорт имён каналов, положений, "\
                              "площадей, размеров и FWHM пиков в формат CSV "\
                              "для любого файла *.FSA/*.HID и экспорт данных"\
                              " внутреннего анализа данных для файлов "\
                              "*.FSA/*.HID, полученных на инструментах ABI "\
                              "3500 и SeqStudio. Также поддерживается чтение"\
                              " нативных файлов Нанофор-05 .frf (крайне "\
                              "экспериментально). Начиная с версии 0.5, "\
                              "поддерживается аллельное бинирование с "\
                              "использованием файлов панелей GeneMapper, "\
                              "GeneMarker и NCBI OSIRIS LadderInfo. При "\
                              "загрузке панели с данными о коэффициентах "\
                              "статтера (файлы GeneMapper Stutter или панели "\
                              "GeneMarker) автоматически применяется "\
                              "фильтрация статтер-пиков. Примечание: панели "\
                              "NCBI OSIRIS не содержат данных о коэффициентах"\
                              " статтера — фильтрация статтера для них "\
                              "недоступна. Также поддерживается экспорт в "\
                              "формат CODIS 3.2 CMF XML (Ctrl+Shift+C): "\
                              "выберите образцы, назначьте категории и "\
                              "метаданные лаборатории — и FragalyseQt "\
                              "сформирует валидный CODISImportFile, готовый"\
                              " к загрузке в базу данных.\n\nПлощади пиков "\
                              "рассчитываются исходя из того, что пики "\
                              "являются гауссовыми.\n\nЛицензировано под "\
                              "GNU AGPL версии 3.\n\nЕсли по какой-либо "\
                              "причине вы хотите проконтактировать с автором"\
                              " - пишите, пожалуйста, на dorif11@gmail.com"
        iface['openfragmentfile'] = "Открыть файл"
        iface['exportinternal'] = "Экспорт Данных Внутреннего Анализа"
        iface['csvexport'] = "Экспорт в CSV"
        iface['exportwholesession'] = "Экспортировать всю сессию"
        iface['choosefolder'] = "Выберите папку для экспорта"
        iface['unsuppeq'] = "Неподдерживаемое оборудование!"
        iface['unsuppeqmsg'] = "Данные внутреннего анализа могут быть "\
                               "экспортированы только из файлов FSA, "\
                               "полученных на ABI 3500 или семействе "\
                               "SeqStudio!"
        iface['dmgdfile'] = "Повреждённый файл!"
        iface['nodatamsg'] = "В файле отсутствуют данные!"
        iface['hidechannel'] = "Скрыть "
        iface['minph'] = "Выберите минимальную высоту пика:"
        iface['minpw'] = "Выберите минимальную ширину пика:"
        iface['minpp'] = "Выберите минимальное возвышение пика:"
        iface['minww'] = "Полуширина окна сглаживания:"
        iface['minpkwl'] = "Ширина окна детекции:"
        iface['minah'] = "Мин. высота аллеля:"
        iface['minah_homo'] = "Мин. высота гомозиготы:"
        iface['menu_view'] = "Вид"
        iface['splitview'] = "Разделить каналы"
        iface['savecsv'] = "Сохранить CSV"
        iface['bcd'] = "Коррекция базовой линии и шумоподавление."
        iface['processbatch'] = "Обработать весь пакет"
        iface['savesession'] = "Сохранить сессию"
        iface['opensession'] = "Открыть сессию"
        iface['savesessiontitle'] = "Сохранить сессию"
        iface['opensessiontitle'] = "Открыть сессию"
        iface['sessionnamelabel'] = "Название сессии:"
        iface['sessionverifytitle'] = "Проверка файлов"
        iface['sessionverifymsg'] = "Один или несколько исходных файлов "\
                                    "отсутствуют или были изменены.\nСессия "\
                                    "будет открыта в режиме только для "\
                                    "чтения с данными из базы данных."
        iface['openreadonly'] = "Открыть только для чтения"
        iface['nosessions'] = "Сохранённые сессии не найдены."
        iface['readonlyplot'] = "Только чтение — исходный файл недоступен"
        iface['wrongsizing'] = "Ошибочный размерный маркер или метод "\
                               "определения размера! Пожалуйста, "\
                               "попробуйте другие!"
        iface['closetab'] = "Закрыть вкладку"
        iface['loadpanel'] = "Загрузить панель"
        iface['nopanel'] = "Панель не загружена"
        iface['allele_col'] = "Аллель"
        iface['loadpaneldlg'] = "Загрузить файл панели"
        iface['loadbinsdlg'] = "Выберите файл бинов"
        iface['nobinsmsg'] = "Файл бинов не найден и не выбран. "\
                             "Для аннотации будут использоваться диапазоны "\
                             "аллелей — конкретные номера аллелей "\
                             "будут недоступны."
        iface['loadstutterdlg'] = "Выберите файл коэффициентов статтера"
        iface['codisexport'] = "Экспорт CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['freq_tables_menu'] = "Таблицы частот"
        iface['ref_profiles_menu'] = "Референсные профили"
        iface['importfreqtable'] = "Импортировать таблицу частот"
        iface['importpanel'] = "Импортировать панель в библиотеку"
        iface['panelimported'] = "Панель(и) сохранены в библиотеку."
        iface['codisdlgtitle'] = "Экспорт CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI назначения:"
        iface['codissourcelab'] = "ID лаборатории-источника:"
        iface['codisanalyst'] = "ID пользователя:"
        iface['codisbatch'] = "ID партии (необяз.):"
        iface['codiskit'] = "Набор (необяз.):"
        iface['codisdt'] = "Дата/время подачи:"
        iface['codisspecimens'] = "Образцы:"
        iface['codisfile'] = "Файл"
        iface['codisspecimenid'] = "ID образца"
        iface['codiscategory'] = "Категория"
        iface['codiscmftitle'] = "Экспорт CODIS CMF"
        iface['codisformat'] = "Формат:"
        iface['codismsgid'] = "ID сообщения:"
        iface['codisinstrid'] = "ID прибора:"
        iface['codismanuf'] = "Производитель:"
        iface['codismodel'] = "Модель:"
        iface['codissoftver'] = "Версия ПО:"
        iface['codisuniqueevent'] = "ID события"
        iface['codisfingerprintdt'] = "Дата/время дактилоскопии"
        iface['codisarrestoffense'] = "Статья обвинения"
        iface['codisrapidvalidation'] = "Для Rapid Import требуются: ORI "\
                                        "назначения, ORI источника, ID "\
                                        "пользователя-создателя, дата/время "\
                                        "сообщения, ID сообщения и ID прибора, "\
                                        "а также для каждого образца: ID "\
                                        "события, дата/время дактилоскопии и "\
                                        "статья обвинения."
        iface['codisnopanel'] = "\u26a0 В некоторых вкладках не загружена панель — "\
                                "данные локусов будут отсутствовать для этих образцов."
        iface['codisnosize'] = "\u26a0 В некоторых вкладках нет пиков с размером — "\
                               "данные локусов будут отсутствовать для этих образцов."
        iface['codisvalidation'] = "Пожалуйста, заполните: ORI назначения, "\
                                   "ID лаборатории, ID пользователя и"\
                                   " дату/время."
        iface['codisemptyid'] = "ID образца не заполнен для одной из "\
                                "выбранных строк."
        iface['codisnorows'] = "Не выбрано ни одного образца для экспорта."
        iface['codissave'] = "Сохранить CODIS XML"
        iface['menu_file'] = "Файл"
        iface['menu_settings'] = "Настройки"
        iface['menu_help'] = "Справка"
        iface['addsizestd'] = "Добавить размерный стандарт"
        iface['stdname'] = "Имя стандарта:"
        iface['stdchannel'] = "Канал ILS (ключ ABIF):"
        iface['stdsizes'] = "Размеры (через пробел):"
        iface['stdimportxml'] = "Импортировать из файла"
        iface['stdimporterr'] = "Не удалось разобрать размерный стандарт из файла."
        iface['stdadded'] = "Размерный стандарт успешно добавлен"
        iface['menu_analysis'] = "Анализ"
        iface['compare_profiles'] = "Сравнение профилей"
        iface['search_profile'] = "Найти в базе данных"
        iface['search_profile_dlg'] = "Поиск профиля в базе"
        iface['search_profile_no_match'] = "Совпадений не найдено."
        iface['search_profile_exact'] = "Точное совпадение"
        iface['search_profile_partial'] = "Частичное"
        iface['search_profile_col_name'] = "Имя"
        iface['search_profile_col_role'] = "Роль"
        iface['search_profile_col_match'] = "Совпало / общих"
        iface['search_profile_col_status'] = "Статус"
        iface['search_profile_query'] = "Искомый профиль:"
        iface['search_profile_nothing_to_search'] = "Нет сохранённых профилей для поиска. Откройте файл или сначала сохраните профиль."
        iface['save_profile'] = "Сохранить профиль в базу"
        iface['save_profile_dlg'] = "Сохранить профиль"
        iface['save_profile_name'] = "Имя:"
        iface['save_profile_role'] = "Роль:"
        iface['save_profile_notes'] = "Примечания (необяз.):"
        iface['save_profile_saved'] = "Профиль сохранён в базу."
        iface['save_profile_empty'] = "Нет аллельных вызовов. Загрузите панель и выполните анализ."
        iface['save_profile_db'] = "База данных:"
        iface['save_profile_db_casework'] = "Кейсы"
        iface['save_profile_db_refprofiles'] = "Референсные профили"
        iface['cmp_title'] = "Сравнение профилей"
        iface['cmp_prof1'] = "Профиль 1:"
        iface['cmp_prof2'] = "Профиль 2:"
        iface['cmp_freqtable'] = "Таблица частот:"
        iface['cmp_import_csv'] = "Импорт CSV."
        iface['cmp_theta'] = "θ (FST):"
        iface['cmp_identity'] = "Идентичность"
        iface['cmp_kinship'] = "Родство"
        iface['cmp_relationship'] = "Тип родства:"
        iface['cmp_calculate'] = "Рассчитать"
        iface['cmp_no_table'] = "Таблица частот не загружена. Сначала импортируйте CSV."
        iface['cmp_no_tabs'] = "Откройте минимум 2 файла для сравнения."
        iface['cmp_nothing_to_compare'] = "Сравнивать пока нечего. Откройте "\
                                          "файлы или сохраните минимум 2 "\
                                          "профиля в базу референсных "\
                                          "профилей."
        iface['cmp_combined_lr'] = "Combined LR:"
        iface['cmp_log10_lr'] = "log₁₀ LR:"
        iface['cmp_conclusion'] = "Вывод:"
        iface['cmp_loci_stat'] = "Локусов типировано: {n}   Исключено: {m}"
        iface['cmp_only_in_1'] = "Только в профиле 1:"
        iface['cmp_only_in_2'] = "Только в профиле 2:"
        iface['cmp_contradicting'] = "Противоречащих локусов: {n}"
        iface['cmp_export_pdf'] = "Экспорт PDF"
        iface['cmp_save_pdf'] = "Сохранить отчёт PDF"
        iface['cmp_export_csv'] = "Экспорт CSV"
        iface['cmp_save_csv'] = "Сохранить CSV сравнения"
        iface['cmp_import_codis'] = "Импорт CODIS XML."
        iface['cmp_codis_imported'] = "Импортировано профилей: {n}."
    elif "ua" in lang:
        iface['ch_inact_msg'] = "Неактивний канал"
        iface['aboutbtn'] = "О програмі"
        iface['infoboxtxt'] = "FragalyseQt версія 0.5.4, кодове ім'я "\
                              "\"Саузерн\".\n\n Версія програми підтримує "\
                              "одночасний аналіз до 8 каналів флуоресценции, "\
                              "вибіркове приховування каналів, не-латинські "\
                              "імена запусків, може правильно працювати з "\
                              "пошкодженими файлами, підтримує експорт імен "\
                              "каналів, положень, площадей, розміру і FWHM "\
                              "піков у формат CSV для будь-якого файла"\
                              " *.FSA/*.HID та експорт даних внутрішнього "\
                              "аналізу даних для файлів *.FSA/*.HID, "\
                              "отриманих на інструментах ABI 3500 и "\
                              "SeqStudio. Також підтримується читання "\
                              "нативних файлів Нанофор-05 .frf (вкрай "\
                              "експериментально). Починаючи з версії 0.5, "\
                              "підтримується алельне бінування з "\
                              "використанням файлів панелей GeneMapper, "\
                              "GeneMarker та NCBI OSIRIS LadderInfo. При "\
                              "завантаженні панелі з даними про коефіцієнти "\
                              "статтера (файли GeneMapper Stutter або панелі "\
                              "GeneMarker) автоматично застосовується "\
                              "фільтрація статтер-піків. Примітка: панелі "\
                              "NCBI OSIRIS не містять даних про коефіцієнти "\
                              "статтера — фільтрація статтера для них "\
                              "недоступна. Також підтримується експорт у "\
                              "формат CODIS 3.2 CMF XML (Ctrl+Shift+C): "\
                              "оберіть зразки, призначте категорії та "\
                              "метадані лабораторії — і FragalyseQt "\
                              "сформує валідний CODISImportFile, готовий"\
                              " до завантаження в базу даних."\
                              "\n\nПлощаді піков розраховуються "\
                              "виходячи з того, що піки є гауссовими.\n\n"\
                              "Ліцензовано під GNU AGPL версії 3.\n\nЯкщо з "\
                              "будь-якої причини ви хочете проконтактувати з "\
                              "автором - пишіть, будь ласка, на "\
                              "dorif11@gmail.com"
        iface['openfragmentfile'] = "Відкрити файл"
        iface['exportinternal'] = "Експорт Даних Внутренього Аналіза"
        iface['csvexport'] = "Експорт в CSV"
        iface['exportwholesession'] = "Експортувати всю сесію"
        iface['choosefolder'] = "Виберіть папку для експорту"
        iface['unsuppeq'] = "Непідтримуване оболаднення!"
        iface['unsuppeqmsg'] = "Дані внутренього аналіза можуть бути "\
                               "експортовані тільки із файлів FSA, отриманих"\
                               " на ABI 3500 або сімействі SeqStudio!"
        iface['dmgdfile'] = "Пошкоджений файл!"
        iface['nodatamsg'] = "У файлі відсутні дані!"
        iface['hidechannel'] = "Сховати "
        iface['minph'] = "Виберіть мінімальну висоту піку:"
        iface['minpw'] = "Виберіть мінімальну ширину піку:"
        iface['minpp'] = "Виберіть мінімальне підвищення піку:"
        iface['minww'] = "Напівширина вікна згладжування:"
        iface['minpkwl'] = "Ширина вікна детекції:"
        iface['minah'] = "Мін. висота алеля:"
        iface['minah_homo'] = "Мін. висота гомозиготи:"
        iface['menu_view'] = "Вигляд"
        iface['splitview'] = "Розділити канали"
        iface['savecsv'] = "Зберегти CSV"
        iface['bcd'] = "Корекція базової лінії та шумозаглушення."
        iface['processbatch'] = "Обробити весь пакет"
        iface['savesession'] = "Зберегти сесію"
        iface['opensession'] = "Відкрити сесію"
        iface['savesessiontitle'] = "Зберегти сесію"
        iface['opensessiontitle'] = "Відкрити сесію"
        iface['sessionnamelabel'] = "Назва сесії:"
        iface['sessionverifytitle'] = "Перевірка файлів"
        iface['sessionverifymsg'] = "Один або кілька вихідних файлів "\
                                    "відсутні або були змінені.\nСесія буде "\
                                    "відкрита у режимі лише для читання з "\
                                    "даними з бази даних."
        iface['openreadonly'] = "Відкрити лише для читання"
        iface['nosessions'] = "Збережених сесій не знайдено."
        iface['readonlyplot'] = "Лише читання — вихідний файл недоступний"
        iface['wrongsizing'] = "Помилковий розмірний маркер чи метод "\
                               "визначення розміру! Будь ласка, спробуйте"\
                               " інші!"
        iface['closetab'] = "Закрити вкладку"
        iface['loadpanel'] = "Завантажити панель"
        iface['nopanel'] = "Панель не завантажена"
        iface['allele_col'] = "Алель"
        iface['loadpaneldlg'] = "Завантажити файл панелі"
        iface['loadbinsdlg'] = "Виберіть файл бінів"
        iface['nobinsmsg'] = "Файл бінів не знайдено і не вибрано. Для "\
                             "анотації будуть використовуватися діапазони "\
                             "алелів — конкретні номери алелів "\
                             "будуть недоступні."
        iface['loadstutterdlg'] = "Виберіть файл коефіцієнтів статера"
        iface['codisexport'] = "Експорт CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['freq_tables_menu'] = "Таблиці частот"
        iface['ref_profiles_menu'] = "Референсні профілі"
        iface['importfreqtable'] = "Імпортувати таблицю частот"
        iface['importpanel'] = "Імпортувати панель до бібліотеки"
        iface['panelimported'] = "Панель(і) збережено до бібліотеки."
        iface['codisdlgtitle'] = "Експорт CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI призначення:"
        iface['codissourcelab'] = "ID лабораторії-джерела:"
        iface['codisanalyst'] = "ID користувача:"
        iface['codisbatch'] = "ID партії (необов.):"
        iface['codiskit'] = "Набір (необов.):"
        iface['codisdt'] = "Дата/час подачі:"
        iface['codisspecimens'] = "Зразки:"
        iface['codisfile'] = "Файл"
        iface['codisspecimenid'] = "ID зразка"
        iface['codiscategory'] = "Категорія"
        iface['codiscmftitle'] = "Експорт CODIS CMF"
        iface['codisformat'] = "Формат:"
        iface['codismsgid'] = "ID повідомлення:"
        iface['codisinstrid'] = "ID приладу:"
        iface['codismanuf'] = "Виробник:"
        iface['codismodel'] = "Модель:"
        iface['codissoftver'] = "Версія ПЗ:"
        iface['codisuniqueevent'] = "ID події"
        iface['codisfingerprintdt'] = "Дата/час дактилоскопії"
        iface['codisarrestoffense'] = "Стаття обвинувачення"
        iface['codisrapidvalidation'] = "Для Rapid Import потрібні: ORI "\
                                        "призначення, ORI джерела, ID "\
                                        "користувача-автора, дата/час "\
                                        "повідомлення, ID повідомлення та ID "\
                                        "приладу, а також для кожного зразка: "\
                                        "ID події, дата/час дактилоскопії та "\
                                        "стаття обвинувачення."
        iface['codisnopanel'] = "\u26a0 У деяких вкладках не завантажено панель — "\
                                "дані локусів будуть відсутні для цих зразків."
        iface['codisnosize'] = "\u26a0 У деяких вкладках немає піків з розміром — "\
                               "дані локусів будуть відсутні для цих зразків."
        iface['codisvalidation'] = "Будь ласка, заповніть: ORI призначення, "\
                                   "ID лабораторії, ID користувача та дату/час."
        iface['codisemptyid'] = "ID зразка не заповнений для одного з вибраних"\
                                " рядків."
        iface['codisnorows'] = "Жодного зразка не вибрано для експорту."
        iface['codissave'] = "Зберегти CODIS XML"
        iface['menu_file'] = "Файл"
        iface['menu_settings'] = "Налаштування"
        iface['menu_help'] = "Довідка"
        iface['addsizestd'] = "Додати розмірний стандарт"
        iface['stdname'] = "Ім'я стандарту:"
        iface['stdchannel'] = "Канал ILS (ключ ABIF):"
        iface['stdsizes'] = "Розміри (через пробіл):"
        iface['stdimportxml'] = "Імпортувати з файлу"
        iface['stdimporterr'] = "Не вдалося розібрати розмірний стандарт із файлу."
        iface['stdadded'] = "Розмірний стандарт успішно додано"
        iface['menu_analysis'] = "Аналіз"
        iface['compare_profiles'] = "Порівняння профілів"
        iface['search_profile'] = "Пошук у базі даних"
        iface['search_profile_dlg'] = "Пошук профілю в базі"
        iface['search_profile_no_match'] = "Збігів не знайдено."
        iface['search_profile_exact'] = "Точний збіг"
        iface['search_profile_partial'] = "Частковий"
        iface['search_profile_col_name'] = "Ім'я"
        iface['search_profile_col_role'] = "Роль"
        iface['search_profile_col_match'] = "Збіглося / спільних"
        iface['search_profile_col_status'] = "Статус"
        iface['search_profile_query'] = "Шуканий профіль:"
        iface['search_profile_nothing_to_search'] = "Немає збережених профілів для пошуку. Відкрийте файл або спершу збережіть профіль."
        iface['save_profile'] = "Зберегти профіль до бази"
        iface['save_profile_dlg'] = "Зберегти профіль"
        iface['save_profile_name'] = "Ім'я:"
        iface['save_profile_role'] = "Роль:"
        iface['save_profile_notes'] = "Примітки (необов.):"
        iface['save_profile_saved'] = "Профіль збережено до бази."
        iface['save_profile_empty'] = "Немає аллельних викликів. Завантажте панель і виконайте аналіз."
        iface['save_profile_db'] = "База даних:"
        iface['save_profile_db_casework'] = "Кейси"
        iface['save_profile_db_refprofiles'] = "Референсні профілі"
        iface['cmp_title'] = "Порівняння профілів"
        iface['cmp_prof1'] = "Профіль 1:"
        iface['cmp_prof2'] = "Профіль 2:"
        iface['cmp_freqtable'] = "Таблиця частот:"
        iface['cmp_import_csv'] = "Імпорт CSV."
        iface['cmp_theta'] = "θ (FST):"
        iface['cmp_identity'] = "Ідентичність"
        iface['cmp_kinship'] = "Спорідненість"
        iface['cmp_relationship'] = "Тип спорідненості:"
        iface['cmp_calculate'] = "Розрахувати"
        iface['cmp_no_table'] = "Таблицю частот не завантажено. Спочатку імпортуйте CSV."
        iface['cmp_no_tabs'] = "Відкрийте щонайменше 2 файли для порівняння."
        iface['cmp_nothing_to_compare'] = "Порівнювати поки нічого. Відкрийте "\
                                          "файли або збережіть щонайменше "\
                                          "2 профілі до бази референсних "\
                                          "профілів."
        iface['cmp_combined_lr'] = "Combined LR:"
        iface['cmp_log10_lr'] = "log₁₀ LR:"
        iface['cmp_conclusion'] = "Висновок:"
        iface['cmp_loci_stat'] = "Локусів типовано: {n}   Виключено: {m}"
        iface['cmp_only_in_1'] = "Лише у профілі 1:"
        iface['cmp_only_in_2'] = "Лише у профілі 2:"
        iface['cmp_contradicting'] = "Суперечливих локусів: {n}"
        iface['cmp_export_pdf'] = "Експорт PDF"
        iface['cmp_save_pdf'] = "Зберегти звіт PDF"
        iface['cmp_export_pdf'] = "Експорт PDF"
        iface['cmp_save_pdf'] = "Запази отчет PDF"
        iface['cmp_export_csv'] = "Експорт CSV"
        iface['cmp_save_csv'] = "Зберегти CSV порівняння"
        iface['cmp_import_codis'] = "Імпорт CODIS XML."
        iface['cmp_codis_imported'] = "Імпортовано профілів: {n}."
    elif "ro" in lang:
        iface['ch_inact_msg'] = "Canal inactiv"
        iface['aboutbtn'] = "Despre program"
        iface['infoboxtxt'] = "FragalyseQt versiune 0.5.4, codename "\
                              "\"Southern\".\n\nAceastă versiune permite "\
                              "analiza simultană a pînă la 8 canale de "\
                              "fluorescență, ascunderea selectivă a canalelor"\
                              ", nume non-latine a runurilor, poate funcționa"\
                              " corect cu fișiere deteriorate, permite "\
                              "exportarea numelor de canale, locațiile, "\
                              "suprafețele, dimensiunile și FWHMurile a "\
                              "vîrfurilor în formatul CSV, pentru orice "\
                              "fișierul de tip *.FSA/*.HID și exportarea în "\
                              "formatul CSV a datelor analizei interne "\
                              "pentru fișiere de tip *.FSA/*.HID generate de "\
                              "echipamentele de model ABI 3500 și SeqStudio."\
                              "De asemenea, sunt acceptate fișierele native "\
                              "Nanophore-05 .frf (foarte experimental). "\
                              "Începând cu versiunea 0.5, este acceptată "\
                              "binarizarea alelelor folosind fișiere de panou"\
                              " GeneMapper, GeneMarker și NCBI OSIRIS"\
                              " LadderInfo. Când se încarcă un panou cu date"\
                              " privind ratele stutter (fișiere GeneMapper"\
                              " Stutter sau panouri GeneMarker), filtrarea"\
                              " vîrfurilor stutter se aplică automat. Notă:"\
                              " panourile NCBI OSIRIS nu conțin date privind"\
                              " ratele stutter — filtrarea stutter nu este"\
                              " disponibilă pentru acestea. De asemenea, este"\
                              " acceptat exportul în formatul CODIS 3.2 CMF "\
                              "XML (Ctrl+Shift+C): selectați probe, atribuiți"\
                              " categorii și metadate de laborator, iar "\
                              "FragalyseQt va genera un CODISImportFile valid"\
                              " pentru încărcare în baza de date.\n\n"\
                              "Suprafețele vîrfurilor, sunt calculate "\
                              "presupunînd că vîrfurile sunt gausiene.\n\n"\
                              "Licențiat sub GNU AGPL versiunea 3.\n\nDacă "\
                              "doriți să contactați autorul, pentru orice "\
                              "întrebare - scrieți, vă rog, la adresa "\
                              "dorif11@gmail.com"
        iface['openfragmentfile'] = "Deschideți fișierul"
        iface['exportinternal'] = "Exportul Datelor Analizei Interne"
        iface['csvexport'] = "Exportul în CSV"
        iface['exportwholesession'] = "Exportă întreaga sesiune"
        iface['choosefolder'] = "Alegeți folderul de export"
        iface['unsuppeq'] = "Echipament nesusținut!"
        iface['unsuppeqmsg'] = "Datele analizei interne pot fi exportate "\
                               "numai pentru fișierile FSA generate de "\
                               "echipamentele de model ABI 3500 și SeqStudio!"
        iface['dmgdfile'] = "Fișier deteriorat!"
        iface['nodatamsg'] = "In fișier lipsesc datele!"
        iface['hidechannel'] = "Ascunde "
        iface['minph'] = "Selectaţi înălţimea minimală a vîrfului:"
        iface['minpw'] = "Selectaţi lăţimea minimală a vîrfului:"
        iface['minpp'] = "Selectaţi proeminenţa minimală a vîrfului:"
        iface['minww'] = "Semi-lăţimea ferestrei de netezire:"
        iface['minpkwl'] = "Lăţimea ferestrei de detecţie:"
        iface['minah'] = "Înălţ. min. alele:"
        iface['minah_homo'] = "Înălţ. min. homozigot:"
        iface['menu_view'] = "Vizualizare"
        iface['splitview'] = "Canale separate"
        iface['savecsv'] = "Salvează CSV"
        iface['bcd'] = "Corectarea liniei de bază și supresia zgomotului."
        iface['processbatch'] = "Procesează tot lotul"
        iface['savesession'] = "Salvează sesiunea"
        iface['opensession'] = "Deschide sesiunea"
        iface['savesessiontitle'] = "Salvează sesiunea"
        iface['opensessiontitle'] = "Deschide sesiunea"
        iface['sessionnamelabel'] = "Numele sesiunii:"
        iface['sessionverifytitle'] = "Verificarea fișierelor"
        iface['sessionverifymsg'] = "Unul sau mai multe fișiere sursă lipsesc "\
                                    "sau au fost modificate.\nSesiunea va fi "\
                                    "deschisă în modul doar citire cu datele "\
                                    "din baza de date."
        iface['openreadonly'] = "Deschide doar citire"
        iface['nosessions'] = "Nu s-au găsit sesiuni salvate."
        iface['readonlyplot'] = "Doar citire — fișierul sursă indisponibil"
        iface['wrongsizing'] = "Marker de dimensiuni sau metodă de "\
                               "dimensionare incorectă! Vă rugăm să"\
                               " încercați altele!"
        iface['closetab'] = "Închide fila"
        iface['loadpanel'] = "Încărcați panoul"
        iface['nopanel'] = "Niciun panou încărcat"
        iface['allele_col'] = "Alelă"
        iface['loadpaneldlg'] = "Încărcați fișierul panoului"
        iface['loadbinsdlg'] = "Selectați fișierul bins"
        iface['nobinsmsg'] = "Niciun fișier bins nu a fost găsit sau "\
                             "selectat. Pentru adnotare vor fi utilizate "\
                             "intervalele de alele — numerele specifice "\
                             "ale alelelor nu vor fi disponibile."
        iface['loadstutterdlg'] = "Selectați fișierul raporturilor stutter"
        iface['codisexport'] = "Export CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['freq_tables_menu'] = "Tabele de frecvențe"
        iface['ref_profiles_menu'] = "Profiluri de referință"
        iface['importfreqtable'] = "Importați tabelul de frecvențe"
        iface['importpanel'] = "Importați panoul în bibliotecă"
        iface['panelimported'] = "Panoul(ele) salvat(e) în bibliotecă."
        iface['codisdlgtitle'] = "Export CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI destinație:"
        iface['codissourcelab'] = "ID laborator sursă:"
        iface['codisanalyst'] = "ID utilizator:"
        iface['codisbatch'] = "ID lot (opț.):"
        iface['codiskit'] = "Kit (opț.):"
        iface['codisdt'] = "Dată/oră depunere:"
        iface['codisspecimens'] = "Specimene:"
        iface['codisfile'] = "Fișier"
        iface['codisspecimenid'] = "ID specimen"
        iface['codiscategory'] = "Categorie"
        iface['codiscmftitle'] = "Export CODIS CMF"
        iface['codisformat'] = "Format:"
        iface['codismsgid'] = "ID mesaj:"
        iface['codisinstrid'] = "ID instrument:"
        iface['codismanuf'] = "Producător:"
        iface['codismodel'] = "Model:"
        iface['codissoftver'] = "Versiune software:"
        iface['codisuniqueevent'] = "ID eveniment"
        iface['codisfingerprintdt'] = "Dată/oră amprentare"
        iface['codisarrestoffense'] = "Infracțiune"
        iface['codisrapidvalidation'] = "Rapid Import necesită: ORI "\
                                        "destinație, ORI sursă, ID utilizator "\
                                        "creator, dată/oră mesaj, ID mesaj și "\
                                        "ID instrument, plus pentru fiecare "\
                                        "specimen: ID eveniment, dată/oră "\
                                        "amprentare și infracțiune."

        iface['codisnopanel'] = "\u26a0 Unele file nu au panou încărcat "\
                                "\u2014 datele locusurilor vor fi absente."
        iface['codisnosize'] = "\u26a0 Unele file nu au vîrfuri cu dimensiune"\
                               " \u2014 datele locusurilor vor fi absente."
        iface['codisvalidation'] = "Completați: ORI destinație, "\
                                   "ID laborator, D utilizator și dată/oră."
        iface['codisemptyid'] = "ID specimen este gol pentru un rând selectat."
        iface['codisnorows'] = "Niciun specimen selectat pentru export."
        iface['codissave'] = "Salvare CODIS XML"
        iface['menu_file'] = "Fișier"
        iface['menu_settings'] = "Setări"
        iface['menu_help'] = "Ajutor"
        iface['addsizestd'] = "Adăugați standardul de mărime"
        iface['stdname'] = "Nume standard:"
        iface['stdchannel'] = "Canal ILS (cheia ABIF):"
        iface['stdsizes'] = "Dimensiuni (separate prin spațiu):"
        iface['stdimportxml'] = "Import din fișier"
        iface['stdimporterr'] = "Nu s-a putut analiza standardul de mărime din fișier."
        iface['stdadded'] = "Standardul de mărime a fost adăugat cu succes"
        iface['menu_analysis'] = "Analiză"
        iface['compare_profiles'] = "Comparare Profiluri"
        iface['search_profile'] = "Căutare în baza de date"
        iface['search_profile_dlg'] = "Căutare profil în baza de date"
        iface['search_profile_no_match'] = "Nu s-au găsit profiluri corespunzătoare."
        iface['search_profile_exact'] = "Potrivire exactă"
        iface['search_profile_partial'] = "Parțial"
        iface['search_profile_col_name'] = "Nume"
        iface['search_profile_col_role'] = "Rol"
        iface['search_profile_col_match'] = "Potriviri / comune"
        iface['search_profile_col_status'] = "Stare"
        iface['search_profile_query'] = "Profil căutat:"
        iface['search_profile_nothing_to_search'] = "Nu există profile salvate pentru căutare. Deschideți un fișier sau salvați mai întâi un profil."
        iface['save_profile'] = "Salvați profilul în baza de date"
        iface['save_profile_dlg'] = "Salvați profilul"
        iface['save_profile_name'] = "Nume:"
        iface['save_profile_role'] = "Rol:"
        iface['save_profile_notes'] = "Note (opțional):"
        iface['save_profile_saved'] = "Profilul a fost salvat în baza de date."
        iface['save_profile_empty'] = "Nu există apeluri de alele. Încărcați un panou și rulați analiza."
        iface['save_profile_db'] = "Baza de date:"
        iface['save_profile_db_casework'] = "Cazuri"
        iface['save_profile_db_refprofiles'] = "Profile de referință"
        iface['cmp_title'] = "Comparare Profiluri"
        iface['cmp_prof1'] = "Profil 1:"
        iface['cmp_prof2'] = "Profil 2:"
        iface['cmp_freqtable'] = "Tabelul frecvențelor:"
        iface['cmp_import_csv'] = "Import CSV."
        iface['cmp_theta'] = "θ (FST):"
        iface['cmp_identity'] = "Identitate"
        iface['cmp_kinship'] = "Rudenie"
        iface['cmp_relationship'] = "Relație:"
        iface['cmp_calculate'] = "Calculați"
        iface['cmp_no_table'] = "Niciun tabel de frecvențe încărcat. Importați mai întâi un CSV."
        iface['cmp_no_tabs'] = "Deschideți cel puțin 2 fișiere pentru comparare."
        iface['cmp_nothing_to_compare'] = "Nimic de comparat deocamdată. "\
                                          "Deschideți fișiere sau salvați cel "\
                                          "puțin 2 profiluri în baza de "\
                                          "profiluri de referință."
        iface['cmp_combined_lr'] = "Combined LR:"
        iface['cmp_log10_lr'] = "log₁₀ LR:"
        iface['cmp_conclusion'] = "Concluzie:"
        iface['cmp_loci_stat'] = "Loci tipizați: {n}   Excluși: {m}"
        iface['cmp_only_in_1'] = "Doar în profilul 1:"
        iface['cmp_only_in_2'] = "Doar în profilul 2:"
        iface['cmp_contradicting'] = "Loci contradictorii: {n}"
        iface['cmp_export_csv'] = "Export CSV"
        iface['cmp_save_csv'] = "Salvați CSV comparare"
        iface['cmp_import_codis'] = "Import XML CODIS."
        iface['cmp_codis_imported'] = "{n} profil(e) importate."
    elif "fr" in lang:
        iface['ch_inact_msg'] = "Canal inactif"
        iface['aboutbtn'] = "Au sujet de"
        iface['infoboxtxt'] = "FragalyseQt version 0.5.4, alias "\
                              "\"Southern\".\n\nCette version du programme "\
                              "prend en charge l'analyse simultanée de "\
                              "jusqu'à 8 canaux de fluorescence différents, "\
                              "le masquage sélectif des canaux, les noms "\
                              "d'exécution non latins et peut gérer "\
                              "correctement les Fichiers endommagés, exporter"\
                              " les emplacements des pics, zones, tailles, "\
                              "FWHM et noms de canal au format CSV pour tous "\
                              "les Fichiers *.FSA/*.HID et exportation au "\
                              "format CSV des données d'analyse interne pour "\
                              "les Fichiers *.FSA/*.HID générés par les "\
                              "équipements des séries ABI 3500 et SeqStudio."\
                              " Prend également en charge les fichiers natifs"\
                              " Nanophore-05 .frf (hautement expérimental)."\
                              " Depuis la version 0.5, le binnage des allèles"\
                              " à l'aide de fichiers de panneaux GeneMapper,"\
                              " GeneMarker et NCBI OSIRIS LadderInfo est pris"\
                              " en charge. Lorsqu'un panneau avec des données"\
                              " de ratios stutter est chargé (fichiers"\
                              " GeneMapper Stutter ou panneaux GeneMarker),"\
                              " le filtrage des pics stutter est appliqué"\
                              " automatiquement. Note : les panneaux NCBI "\
                              "OSIRIS ne contiennent pas de données de ratios"\
                              " stutter — le filtrage stutter n'est pas"\
                              " disponible pour eux. L'export au"\
                              " format CODIS 3.2 CMF XML est également"\
                              " disponible (Ctrl+Shift+C) : sélectionnez les"\
                              " échantillons, attribuez les catégories et"\
                              " métadonnées du laboratoire, et FragalyseQt"\
                              " génèrera un CODISImportFile valide prêt pour"\
                              " la soumission.\n\nLes zones de pics sont"\
                              " calculées en "\
                              "supposant qu'il s'agit de pics gaussiens.\n\n"\
                              "Licence sous GNU AGPL version 3.\n\nSi vous "\
                              "souhaitez contacter l'auteur pour une raison "\
                              "quelconque, veuillez écrire à dorif11@gmail.com"
        iface['openfragmentfile'] = "Ouvrer le Fichier"
        iface['exportinternal'] = "Exporter des données d'analyse interne"
        iface['csvexport'] = "Exporter en CSV"
        iface['exportwholesession'] = "Exporter toute la session"
        iface['choosefolder'] = "Choisissez le dossier d'export"
        iface['unsuppeq'] = "L'équipement non supportés!"
        iface['unsuppeqmsg'] = "Les données d'analyse internes ne pouvaient "\
                               "être exportées qu'à partir de Fichiers FSA "\
                               "générés par les séquenceurs de la famille "\
                               "ABI 3500 et SeqStudio!"
        iface['dmgdfile'] = "Fichier endommagé!"
        iface['nodatamsg'] = "Il n'y a pas de données dans le Fichier!"
        iface['hidechannel'] = "Masquer"
        iface['minph'] = "Sélectionnez la hauteur de pic minimale:"
        iface['minpw'] = "Sélectionnez la largeur de pic minimale:"
        iface['minpp'] = "Sélectionnez la proéminence de pic minimale:"
        iface['minww'] = "Demi-largeur de la fenêtre de lissage:"
        iface['minpkwl'] = "Largeur de la fenêtre de détection:"
        iface['minah'] = "Haut. min. allèle:"
        iface['minah_homo'] = "Haut. min. homozygote :"
        iface['menu_view'] = "Affichage"
        iface['splitview'] = "Canaux séparés"
        iface['savecsv'] = "Enregistrer CSV"
        iface['bcd'] = "Correction de la ligne de base et suppression du"\
                       " bruit."
        iface['processbatch'] = "Traiter tout le lot"
        iface['savesession'] = "Enregistrer la session"
        iface['opensession'] = "Ouvrir la session"
        iface['savesessiontitle'] = "Enregistrer la session"
        iface['opensessiontitle'] = "Ouvrir la session"
        iface['sessionnamelabel'] = "Nom de la session :"
        iface['sessionverifytitle'] = "Vérification des fichiers"
        iface['sessionverifymsg'] = "Un ou plusieurs fichiers sources sont "\
                                    "manquants ou ont été modifiés.\nLa session "\
                                    "s'ouvrira en lecture seule avec les données "\
                                    "stockées dans la base de données."
        iface['openreadonly'] = "Ouvrir en lecture seule"
        iface['nosessions'] = "Aucune session sauvegardée trouvée."
        iface['readonlyplot'] = "Lecture seule — fichier source indisponible"
        iface['wrongsizing'] = "Marqueur de dimensionnement ou méthode de "\
                               "dimensionnement incorrect ! S'il vous plaît"\
                               ", essayez-en d'autres !"
        iface['closetab'] = "Fermer l'onglet"
        iface['loadpanel'] = "Charger le panneau"
        iface['nopanel'] = "Aucun panneau chargé"
        iface['allele_col'] = "Allèle"
        iface['loadpaneldlg'] = "Charger le fichier de panneau"
        iface['loadbinsdlg'] = "Sélectionner le fichier bins"
        iface['nobinsmsg'] = "Aucun fichier bins n'a été trouvé ou "\
                             "sélectionné. Les plages d'allèles seront "\
                             "utilisées pour l'annotation — les numéros "\
                             "d'allèles spécifiques ne seront pas disponibles."
        iface['loadstutterdlg'] = "Sélectionner le fichier de ratios stutter"
        iface['codisexport'] = "Exporter CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['freq_tables_menu'] = "Tables de fréquences"
        iface['ref_profiles_menu'] = "Profils de référence"
        iface['importfreqtable'] = "Importer la table de fréquences"
        iface['importpanel'] = "Importer le panneau dans la bibliothèque"
        iface['panelimported'] = "Panneau(x) enregistré(s) dans la bibliothèque."
        iface['codisdlgtitle'] = "Export CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI destinataire :"
        iface['codissourcelab'] = "ID laboratoire source :"
        iface['codisanalyst'] = "ID utilisateur :"
        iface['codisbatch'] = "ID lot (opt.) :"
        iface['codiskit'] = "Kit (opt.) :"
        iface['codisdt'] = "Date/heure dépôt :"
        iface['codisspecimens'] = "Spécimens :"
        iface['codisfile'] = "Fichier"
        iface['codisspecimenid'] = "ID spécimen"
        iface['codiscategory'] = "Catégorie"
        iface['codiscmftitle'] = "Export CODIS CMF"
        iface['codisformat'] = "Format :"
        iface['codismsgid'] = "ID du message :"
        iface['codisinstrid'] = "ID de l'instrument :"
        iface['codismanuf'] = "Fabricant :"
        iface['codismodel'] = "Modèle :"
        iface['codissoftver'] = "Version du logiciel :"
        iface['codisuniqueevent'] = "ID d'événement"
        iface['codisfingerprintdt'] = "Date/heure des empreintes"
        iface['codisarrestoffense'] = "Infraction"
        iface['codisrapidvalidation'] = "Rapid Import requiert : ORI "\
                                        "destinataire, ORI source, ID "\
                                        "utilisateur créateur, date/heure du "\
                                        "message, ID du message et ID de "\
                                        "l'instrument, ainsi que pour chaque "\
                                        "spécimen : ID d'événement, date/heure "\
                                        "des empreintes et infraction."
        iface['codisnopanel'] = "\u26a0 Certains onglets n\'ont pas de panneau"\
                                " — les données de locus seront absentes."
        iface['codisnosize'] = "\u26a0 Certains onglets n\'ont pas de pics dimensionnés"\
                               " — les données de locus seront absentes."
        iface['codisvalidation'] = "Veuillez remplir : ORI destinataire, ID laboratoire,"\
                                   " ID utilisateur et date/heure."
        iface['codisemptyid'] = "L\'ID spécimen est vide pour une ligne sélectionnée."
        iface['codisnorows'] = "Aucun spécimen sélectionné pour l\'export."
        iface['codissave'] = "Enregistrer CODIS XML"
        iface['menu_file'] = "Fichier"
        iface['menu_settings'] = "Paramètres"
        iface['menu_help'] = "Aide"
        iface['addsizestd'] = "Ajouter un standard de taille"
        iface['stdname'] = "Nom du standard:"
        iface['stdchannel'] = "Canal ILS (clé ABIF):"
        iface['stdsizes'] = "Tailles (séparées par des espaces):"
        iface['stdimportxml'] = "Importer depuis un fichier"
        iface['stdimporterr'] = "Impossible d'analyser le standard de taille depuis le fichier."
        iface['stdadded'] = "Standard de taille ajouté avec succès"
        iface['menu_analysis'] = "Analyse"
        iface['compare_profiles'] = "Comparer les profils"
        iface['search_profile'] = "Rechercher dans la base"
        iface['search_profile_dlg'] = "Recherche de profil dans la base"
        iface['search_profile_no_match'] = "Aucun profil correspondant trouvé."
        iface['search_profile_exact'] = "Correspondance exacte"
        iface['search_profile_partial'] = "Partielle"
        iface['search_profile_col_name'] = "Nom"
        iface['search_profile_col_role'] = "Rôle"
        iface['search_profile_col_match'] = "Concordances / communs"
        iface['search_profile_col_status'] = "Statut"
        iface['search_profile_query'] = "Profil recherché :"
        iface['search_profile_nothing_to_search'] = "Aucun profil enregistré pour la recherche. Ouvrez un fichier ou enregistrez d'abord un profil."
        iface['save_profile'] = "Enregistrer le profil dans la base"
        iface['save_profile_dlg'] = "Enregistrer le profil"
        iface['save_profile_name'] = "Nom :"
        iface['save_profile_role'] = "Rôle :"
        iface['save_profile_notes'] = "Notes (facultatif) :"
        iface['save_profile_saved'] = "Profil enregistré dans la base."
        iface['save_profile_empty'] = "Aucun appel d'allèles. Chargez un panneau et lancez l'analyse."
        iface['save_profile_db'] = "Base de données :"
        iface['save_profile_db_casework'] = "Affaires"
        iface['save_profile_db_refprofiles'] = "Profils de référence"
        iface['cmp_title'] = "Comparaison de profils"
        iface['cmp_prof1'] = "Profil 1 :"
        iface['cmp_prof2'] = "Profil 2 :"
        iface['cmp_freqtable'] = "Table de fréquences :"
        iface['cmp_import_csv'] = "Importer CSV."
        iface['cmp_theta'] = "θ (FST) :"
        iface['cmp_identity'] = "Identité"
        iface['cmp_kinship'] = "Parenté"
        iface['cmp_relationship'] = "Relation :"
        iface['cmp_calculate'] = "Calculer"
        iface['cmp_no_table'] = "Aucune table de fréquences chargée. Importez un CSV d'abord."
        iface['cmp_no_tabs'] = "Ouvrez au moins 2 fichiers pour comparer."
        iface['cmp_nothing_to_compare'] = "Rien à comparer pour l'instant. "\
                                          "Ouvrez des fichiers ou enregistrez "\
                                          "au moins 2 profils dans la base "\
                                          "de profils de référence."
        iface['cmp_combined_lr'] = "Combined LR :"
        iface['cmp_log10_lr'] = "log₁₀ LR :"
        iface['cmp_conclusion'] = "Conclusion :"
        iface['cmp_loci_stat'] = "Loci typés : {n}   Exclus : {m}"
        iface['cmp_only_in_1'] = "Uniquement dans le profil 1 :"
        iface['cmp_only_in_2'] = "Uniquement dans le profil 2 :"
        iface['cmp_contradicting'] = "Loci contradictoires : {n}"
        iface['cmp_export_pdf'] = "Exporter PDF"
        iface['cmp_save_pdf'] = "Enregistrer rapport PDF"
        iface['cmp_export_csv'] = "Exporter CSV"
        iface['cmp_save_csv'] = "Enregistrer CSV comparaison"
        iface['cmp_import_codis'] = "Importer XML CODIS."
        iface['cmp_codis_imported'] = "{n} profil(s) importé(s)."
    elif "bg" in lang:
        iface['ch_inact_msg'] = "Неактивен канал"
        iface['aboutbtn'] = "Относно програмата"
        iface['infoboxtxt'] = "FragalyseQt версия 0.5.4, кодово име \"Саузерн"\
                              "\".\n\nТази версия на програмата поддържа "\
                              "едновременен анализ до 8 флуоресцентни канала,"\
                              " селективно скриване на канали, не-латински "\
                              "имена на изпълнения, може да работи правилно с"\
                              " повредени файлове, поддържа експорт на имена "\
                              "на канали, позиции, площите, размери и FWHM "\
                              "пикове в CSV формат за всеки *.FSA/*.HID файл "\
                              "и експортиране на вътрешни данни за анализ на "\
                              "данни за *.FSA/*.HID файлове, получени с ABI "\
                              "3500 и инструменти SeqStudio. Поддържа се и "\
                              "четене на нативни файлове Nanophore-05 .frf "\
                              "(силно експериментално). Считано от версия "\
                              "0.5, се поддържа алелно биниране с помощта на"\
                              " файлове с панели GeneMapper, GeneMarker и"\
                              " NCBI OSIRIS LadderInfo. При зареждане на"\
                              " панел с данни за коефициенти на статер"\
                              " (GeneMapper Stutter файлове или GeneMarker"\
                              " панели) автоматично се прилага филтриране на"\
                              " статер пикове. Забележка: NCBI OSIRIS"\
                              " панелите не съдържат данни за коефициенти на"\
                              " статер — филтрирането на статер не е налично"\
                              " за тях. Поддържа се и експорт във формат"\
                              " CODIS 3.2"\
                              " CMF XML (Ctrl+Shift+C): изберете проби,"\
                              " задайте категории и метаданни на"\
                              " лабораторията — FragalyseQt ще генерира"\
                              " валиден CODISImportFile, готов за подаване."\
                              "\n\nПлощите на "\
                              "пиковете се изчисляват, като се приема, че "\
                              "пиковете са гаусови.\n\nЛицензирано под GNU "\
                              "AGPL версия 3.\n\nАко по някаква причина "\
                              "искате да се свържете с автора, моля, "\
                              "изпратете имейл на dorif11@gmail.com"
        iface['openfragmentfile'] = "Отвори файла"
        iface['exportinternal'] = "Експорт на Данни от Вътрешен Анализ"
        iface['csvexport'] = "Експорт в CSV"
        iface['exportwholesession'] = "Експортиране на цялата сесия"
        iface['choosefolder'] = "Изберете папка за експорт"
        iface['unsuppeq'] = "Неподдържан оборудване!"
        iface['unsuppeqmsg'] = "Данните за вътрешен анализ могат да бъдат "\
                               "експортирани само от файлове FSA, придобити "\
                               "на ABI 3500 или фамилията SeqStudio!"
        iface['dmgdfile'] = "Повреден файл!"
        iface['nodatamsg'] = "Във файла няма данни!"
        iface['hidechannel'] = "Крия "
        iface['minph'] = "Изберете минимална височина на върха:"
        iface['minpw'] = "Изберете минимална ширина на върха:"
        iface['minpp'] = "Изберете минимална надморска височина:"
        iface['minww'] = "Полуширина на прозореца за изглаждане:"
        iface['minpkwl'] = "Ширина на прозореца за детекция:"
        iface['minah'] = "Мин. вис. алел:"
        iface['minah_homo'] = "Мин. вис. хомозигота:"
        iface['menu_view'] = "Изглед"
        iface['splitview'] = "Разделени канали"
        iface['savecsv'] = "Запазване на CSV"
        iface['bcd'] = "Корекция на базовата линия и шумопотискане."
        iface['processbatch'] = "Обработка на целия пакет"
        iface['savesession'] = "Запазване на сесията"
        iface['opensession'] = "Отваряне на сесия"
        iface['savesessiontitle'] = "Запазване на сесията"
        iface['opensessiontitle'] = "Отваряне на сесия"
        iface['sessionnamelabel'] = "Име на сесията:"
        iface['sessionverifytitle'] = "Проверка на файловете"
        iface['sessionverifymsg'] = "Един или повече изходни файлове липсват "\
                                    "или са били променени.\nСесията ще се "\
                                    "отвори в режим само за четене с данните "\
                                    "от базата данни."
        iface['openreadonly'] = "Отвори само за четене"
        iface['nosessions'] = "Няма запазени сесии."
        iface['readonlyplot'] = "Само четене — изходният файл е недостъпен"
        iface['wrongsizing'] = "Неправилен маркер за оразмеряване или метод"\
                               " за оразмеряване! Моля, опитайте други!"
        iface['closetab'] = "Затвори раздела"
        iface['loadpanel'] = "Зареди панела"
        iface['nopanel'] = "Не е зареден панел"
        iface['allele_col'] = "Алел"
        iface['loadpaneldlg'] = "Зареди файл с панела"
        iface['loadbinsdlg'] = "Изберете файл с бинове"
        iface['nobinsmsg'] = "Не е намерен или избран файл с бинове. "\
                             "За анотиране ще се използват диапазони на "\
                             "алелите — конкретни номера на алелите "\
                             "няма да бъдат налични."
        iface['loadstutterdlg'] = "Изберете файл с коефициенти на статер"
        iface['codisexport'] = "Експорт CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Импортиране на панела в библиотеката"
        iface['panelimported'] = "Панел(ите) е(са) запазен(и) в библиотеката."
        iface['codisdlgtitle'] = "Експорт CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI получател:"
        iface['codissourcelab'] = "ID лаборатория-източник:"
        iface['codisanalyst'] = "ID потребител:"
        iface['codisbatch'] = "ID партида (незадълж.):"
        iface['codiskit'] = "Комплект (незадълж.):"
        iface['codisdt'] = "Дата/час на подаване:"
        iface['codisspecimens'] = "Образци:"
        iface['codisfile'] = "Файл"
        iface['codisspecimenid'] = "ID образец"
        iface['codiscategory'] = "Категория"
        iface['codiscmftitle'] = "Експорт на CODIS CMF"
        iface['codisformat'] = "Формат:"
        iface['codismsgid'] = "ID на съобщение:"
        iface['codisinstrid'] = "ID на инструмент:"
        iface['codismanuf'] = "Производител:"
        iface['codismodel'] = "Модел:"
        iface['codissoftver'] = "Версия на софтуера:"
        iface['codisuniqueevent'] = "ID на събитие"
        iface['codisfingerprintdt'] = "Дата/час на дактилоскопия"
        iface['codisarrestoffense'] = "Престъпление"
        iface['codisrapidvalidation'] = "Rapid Import изисква: ORI "\
                                        "местоназначение, ORI източник, ID на "\
                                        "потребителя-създател, дата/час на "\
                                        "съобщението, ID на съобщението и ID "\
                                        "на инструмента, както и за всеки "\
                                        "образец: ID на събитие, дата/час на "\
                                        "дактилоскопия и престъпление."
        iface['codisnopanel'] = "\u26a0 Някои раздели нямат заредена панел — "\
                                "данните за локуси ще липсват за тези образци."
        iface['codisnosize'] = "\u26a0 Някои раздели нямат пикове с размер — "\
                               "данните за локуси ще липсват за тези образци."
        iface['codisvalidation'] = "Моля, попълнете: ORI получател, ID "\
                                   "лаборатория, ID потребител и дата/час."
        iface['codisemptyid'] = "ID образец е празен за избран ред."
        iface['codisnorows'] = "Не са избрани образци за експорт."
        iface['codissave'] = "Запазване на CODIS XML"
        iface['menu_file'] = "Файл"
        iface['menu_settings'] = "Настройки"
        iface['menu_help'] = "Помощ"
        iface['addsizestd'] = "Добавяне на размерен стандарт"
        iface['stdname'] = "Име на стандарта:"
        iface['stdchannel'] = "ILS канал (ABIF ключ):"
        iface['stdsizes'] = "Размери (разделени с интервал):"
        iface['stdimportxml'] = "Импортиране от файл"
        iface['stdimporterr'] = "Неуспешно четене на размерен стандарт от файла."
        iface['stdadded'] = "Размерният стандарт е добавен успешно"
        iface['menu_analysis'] = "Анализ"
        iface['compare_profiles'] = "Сравнение на профили"
        iface['search_profile'] = "Търсене в базата данни"
        iface['search_profile_dlg'] = "Търсене на профил в базата"
        iface['search_profile_no_match'] = "Не са намерени съответстващи профили."
        iface['search_profile_exact'] = "Точно съвпадение"
        iface['search_profile_partial'] = "Частично"
        iface['search_profile_col_name'] = "Име"
        iface['search_profile_col_role'] = "Роля"
        iface['search_profile_col_match'] = "Съвпаднали / общи"
        iface['search_profile_col_status'] = "Статус"
        iface['search_profile_query'] = "Търсен профил:"
        iface['search_profile_nothing_to_search'] = "Няма запазени профили за търсене. Отворете файл или първо запазете профил."
        iface['save_profile'] = "Запази профил в базата"
        iface['save_profile_dlg'] = "Запази профил"
        iface['save_profile_name'] = "Име:"
        iface['save_profile_role'] = "Роля:"
        iface['save_profile_notes'] = "Бележки (по избор):"
        iface['save_profile_saved'] = "Профилът е запазен в базата."
        iface['save_profile_empty'] = "Няма аллелни извиквания. Заредете панел и стартирайте анализа."
        iface['save_profile_db'] = "База данни:"
        iface['save_profile_db_casework'] = "Случаи"
        iface['save_profile_db_refprofiles'] = "Референтни профили"
        iface['cmp_title'] = "Сравнение на профили"
        iface['cmp_prof1'] = "Профил 1:"
        iface['cmp_prof2'] = "Профил 2:"
        iface['cmp_freqtable'] = "Таблица с честоти:"
        iface['cmp_import_csv'] = "Импорт CSV."
        iface['cmp_theta'] = "θ (FST):"
        iface['cmp_identity'] = "Идентичност"
        iface['cmp_kinship'] = "Родство"
        iface['cmp_relationship'] = "Вид родство:"
        iface['cmp_calculate'] = "Изчисли"
        iface['cmp_no_table'] = "Таблицата с честоти не е заредена. Първо импортирайте CSV."
        iface['cmp_no_tabs'] = "Отворете поне 2 файла за сравнение."
        iface['cmp_nothing_to_compare'] = "Няма какво да се сравнява засега. "\
                                          "Отворете файлове или запазете поне "\
                                          "2 профила в базата с референтни "\
                                          "профили."
        iface['cmp_combined_lr'] = "Combined LR:"
        iface['cmp_log10_lr'] = "log₁₀ LR:"
        iface['cmp_conclusion'] = "Заключение:"
        iface['cmp_loci_stat'] = "Типирани локуси: {n}   Изключени: {m}"
        iface['cmp_only_in_1'] = "Само в профил 1:"
        iface['cmp_only_in_2'] = "Само в профил 2:"
        iface['cmp_contradicting'] = "Противоречащи локуси: {n}"
        iface['cmp_export_csv'] = "Експорт CSV"
        iface['cmp_save_csv'] = "Запази CSV за сравнение"
        iface['cmp_import_codis'] = "Импорт CODIS XML."
        iface['cmp_codis_imported'] = "Импортирани профили: {n}."
    elif "de" in lang:
        iface['ch_inact_msg'] = "Inaktiver Kanal"
        iface['aboutbtn'] = "Über das Programm"
        iface['infoboxtxt'] = "FragalyseQt Version 0.5.4, Codename "\
                              "\"Southern\".\n\nDiese Programmversion "\
                              "unterstützt die gleichzeitige Analyse von bis "\
                              "zu 8 verschiedenen Fluoreszenzkanälen, "\
                              "selektives Ausblenden von Kanälen, "\
                              "nicht-lateinische Laufnamen, kann beschädigte "\
                              "Dateien korrekt verarbeiten, unterstützt den "\
                              "Export von Kanalnamen, Peak-Positionen, "\
                              "Flächen, Größen und FWHM-Werten im CSV-Format "\
                              "für jede *.FSA/*.HID-Datei sowie den Export "\
                              "interner Analysedaten für *.FSA/*.HID-Dateien "\
                              "von ABI 3500 und SeqStudio-Geräten. Außerdem "\
                              "wird das Lesen nativer Nanophore-05 .frf-"\
                              "Dateien unterstützt (hochgradig "\
                              "experimentell). Ab Version 0.5 wird "\
                              "Allel-Binning mittels GeneMapper-, GeneMarker-"\
                              " und NCBI-OSIRIS-LadderInfo-Panel-Dateien"\
                              " unterstützt. Wenn ein Panel mit"\
                              " Stutter-Verhältnis-Daten geladen wird"\
                              " (GeneMapper-Stutter-Dateien oder"\
                              " GeneMarker-Panels), wird die Filterung von"\
                              " Stutter-Peaks automatisch angewendet."\
                              " Hinweis: NCBI-OSIRIS-Panels enthalten keine"\
                              " Stutter-Verhältnis-Daten — die"\
                              " Stutter-Filterung ist für sie nicht verfügbar"\
                              ". Der Export im Format CODIS 3.2 CMF XML wird"\
                              " ebenfalls unterstützt (Ctrl+Shift+C):"\
                              " Proben auswählen, Kategorien und"\
                              " Labormetadaten zuweisen — FragalyseQt"\
                              " erstellt eine valide CODISImportFile-Datei"\
                              " zur Einreichung in die Datenbank."\
                              "\n\nPeak-Flächen werden unter der Annahme "\
                              "berechnet, dass es sich um Gaußsche Peaks "\
                              "handelt.\n\nLizenziert unter GNU AGPL "\
                              "Version 3.\n\nWenn Sie den Autor kontaktieren "\
                              "möchten, schreiben Sie bitte an "\
                              "dorif11@gmail.com"
        iface['openfragmentfile'] = "Datei öffnen"
        iface['exportinternal'] = "Interne Analysedaten exportieren"
        iface['csvexport'] = "Als CSV exportieren"
        iface['exportwholesession'] = "Gesamte Sitzung exportieren"
        iface['choosefolder'] = "Exportordner auswählen"
        iface['unsuppeq'] = "Nicht unterstütztes Gerät!"
        iface['unsuppeqmsg'] = "Interne Analysedaten können nur aus "\
                               "FSA-Dateien exportiert werden, die von "\
                               "ABI 3500 oder SeqStudio-Geräten erzeugt "\
                               "wurden!"
        iface['dmgdfile'] = "Beschädigte Datei!"
        iface['nodatamsg'] = "Die Datei enthält keine Daten!"
        iface['hidechannel'] = "Kanal ausblenden "
        iface['minph'] = "Minimale Peakhöhe auswählen:"
        iface['minpw'] = "Minimale Peakbreite auswählen:"
        iface['minpp'] = "Minimale Peakprominenz auswählen:"
        iface['minww'] = "Halbbreite des Glättungsfensters:"
        iface['minpkwl'] = "Detektionsfensterbreite:"
        iface['minah'] = "Min. Allel-Höhe:"
        iface['minah_homo'] = "Min. Homozygot-Höhe:"
        iface['menu_view'] = "Ansicht"
        iface['splitview'] = "Kanäle trennen"
        iface['savecsv'] = "CSV speichern"
        iface['bcd'] = "Basislinienkorrektur und Rauschunterdrückung."
        iface['processbatch'] = "Gesamten Stapel verarbeiten"
        iface['savesession'] = "Sitzung speichern"
        iface['opensession'] = "Sitzung öffnen"
        iface['savesessiontitle'] = "Sitzung speichern"
        iface['opensessiontitle'] = "Sitzung öffnen"
        iface['sessionnamelabel'] = "Sitzungsname:"
        iface['sessionverifytitle'] = "Dateiüberprüfung"
        iface['sessionverifymsg'] = "Eine oder mehrere Quelldateien fehlen "\
                                    "oder wurden geändert.\nDie Sitzung wird "\
                                    "im Nur-Lese-Modus mit den in der Datenbank "\
                                    "gespeicherten Daten geöffnet."
        iface['openreadonly'] = "Nur lesend öffnen"
        iface['nosessions'] = "Keine gespeicherten Sitzungen gefunden."
        iface['readonlyplot'] = "Nur Lesen — Quelldatei nicht verfügbar"
        iface['wrongsizing'] = "Falsche Leiter oder Größenbestimmungs"\
                               "methode! Bitte versuchen Sie andere!"
        iface['closetab'] = "Registerkarte schließen"
        iface['loadpanel'] = "Panel laden"
        iface['nopanel'] = "Kein Panel geladen"
        iface['allele_col'] = "Allel"
        iface['loadpaneldlg'] = "Panel-Datei laden"
        iface['loadbinsdlg'] = "Bins-Datei auswählen"
        iface['nobinsmsg'] = "Keine Bins-Datei gefunden oder ausgewählt. "\
                             "Für die Annotation werden Allel-Bereiche "\
                             "verwendet — spezifische Allel-Nummern "\
                             "sind nicht verfügbar."
        iface['loadstutterdlg'] = "Stutter-Verhältnis-Datei auswählen"
        iface['codisexport'] = "CODIS XML exportieren"
        iface['soapapimenu'] = "SOAP API"
        iface['freq_tables_menu'] = "Häufigkeitstabellen"
        iface['ref_profiles_menu'] = "Referenzprofile"
        iface['importfreqtable'] = "Häufigkeitstabelle importieren"
        iface['importpanel'] = "Panel in Bibliothek importieren"
        iface['panelimported'] = "Panel(s) in Bibliothek gespeichert."
        iface['codisdlgtitle'] = "CODIS 3.2 CMF Export"
        iface['codisdestori'] = "Ziel-ORI:"
        iface['codissourcelab'] = "Quell-Labor-ID:"
        iface['codisanalyst'] = "Benutzer-ID:"
        iface['codisbatch'] = "Chargen-ID (opt.):"
        iface['codiskit'] = "Kit (opt.):"
        iface['codisdt'] = "Einreichungsdatum/-zeit:"
        iface['codisspecimens'] = "Proben:"
        iface['codisfile'] = "Datei"
        iface['codisspecimenid'] = "Proben-ID"
        iface['codiscategory'] = "Kategorie"
        iface['codiscmftitle'] = "CODIS-CMF-Export"
        iface['codisformat'] = "Format:"
        iface['codismsgid'] = "Nachrichten-ID:"
        iface['codisinstrid'] = "Geräte-ID:"
        iface['codismanuf'] = "Hersteller:"
        iface['codismodel'] = "Modell:"
        iface['codissoftver'] = "Softwareversion:"
        iface['codisuniqueevent'] = "Ereignis-ID"
        iface['codisfingerprintdt'] = "Datum/Uhrzeit der Fingerabdrücke"
        iface['codisarrestoffense'] = "Straftat"
        iface['codisrapidvalidation'] = "Rapid Import erfordert: Ziel-ORI, "\
                                        "Quell-ORI, Ersteller-Benutzer-ID, "\
                                        "Nachrichtendatum/-zeit, "\
                                        "Nachrichten-ID und Geräte-ID sowie "\
                                        "pro Probe: Ereignis-ID, "\
                                        "Datum/Uhrzeit der Fingerabdrücke und "\
                                        "Straftat."
        iface['codisnopanel'] = "\u26a0 Einige Tabs haben kein Panel — "\
                                "Locus-Daten fehlen für diese Proben."
        iface['codisnosize'] = "\u26a0 Einige Tabs haben keine dimensionierten"\
                               " Peaks — Locus-Daten fehlen für diese Proben."
        iface['codisvalidation'] = "Bitte ausfüllen: Ziel-ORI, Quell-Labor-ID"\
                                   ", Benutzer-ID und Datum/Uhrzeit."
        iface['codisemptyid'] = "Proben-ID ist leer für eine ausgewählte Zeile."
        iface['codisnorows'] = "Keine Proben für den Export ausgewählt."
        iface['codissave'] = "CODIS XML speichern"
        iface['menu_file'] = "Datei"
        iface['menu_settings'] = "Einstellungen"
        iface['menu_help'] = "Hilfe"
        iface['addsizestd'] = "Größenstandard hinzufügen"
        iface['stdname'] = "Standardname:"
        iface['stdchannel'] = "ILS-Kanal (ABIF-Schlüssel):"
        iface['stdsizes'] = "Größen (leerzeichengetrennt):"
        iface['stdimportxml'] = "Aus Datei importieren"
        iface['stdimporterr'] = "Größenstandard konnte nicht aus der Datei gelesen werden."
        iface['stdadded'] = "Größenstandard erfolgreich hinzugefügt"
        iface['menu_analysis'] = "Analyse"
        iface['compare_profiles'] = "Profile vergleichen"
        iface['search_profile'] = "In Datenbank suchen"
        iface['search_profile_dlg'] = "Profil in Datenbank suchen"
        iface['search_profile_no_match'] = "Keine übereinstimmenden Profile gefunden."
        iface['search_profile_exact'] = "Genaue Übereinstimmung"
        iface['search_profile_partial'] = "Teilweise"
        iface['search_profile_col_name'] = "Name"
        iface['search_profile_col_role'] = "Rolle"
        iface['search_profile_col_match'] = "Übereinstimmend / gemeinsam"
        iface['search_profile_col_status'] = "Status"
        iface['search_profile_query'] = "Suchprofil:"
        iface['search_profile_nothing_to_search'] = "Keine gespeicherten Profile für die Suche. Öffnen Sie eine Datei oder speichern Sie zuerst ein Profil."
        iface['save_profile'] = "Profil in Datenbank speichern"
        iface['save_profile_dlg'] = "Profil speichern"
        iface['save_profile_name'] = "Name:"
        iface['save_profile_role'] = "Rolle:"
        iface['save_profile_notes'] = "Notizen (optional):"
        iface['save_profile_saved'] = "Profil in Datenbank gespeichert."
        iface['save_profile_empty'] = "Keine Allel-Aufrufe. Laden Sie ein Panel und führen Sie die Analyse durch."
        iface['save_profile_db'] = "Datenbank:"
        iface['save_profile_db_casework'] = "Fallarbeit"
        iface['save_profile_db_refprofiles'] = "Referenzprofile"
        iface['cmp_title'] = "Profilvergleich"
        iface['cmp_prof1'] = "Profil 1:"
        iface['cmp_prof2'] = "Profil 2:"
        iface['cmp_freqtable'] = "Häufigkeitstabelle:"
        iface['cmp_import_csv'] = "CSV importieren."
        iface['cmp_theta'] = "θ (FST):"
        iface['cmp_identity'] = "Identität"
        iface['cmp_kinship'] = "Verwandtschaft"
        iface['cmp_relationship'] = "Beziehung:"
        iface['cmp_calculate'] = "Berechnen"
        iface['cmp_no_table'] = "Keine Häufigkeitstabelle geladen. Importieren Sie zuerst eine CSV."
        iface['cmp_no_tabs'] = "Öffnen Sie mindestens 2 Dateien zum Vergleichen."
        iface['cmp_nothing_to_compare'] = "Noch nichts zu vergleichen. Öffnen "\
                                          "Sie Dateien oder speichern Sie "\
                                          "mindestens 2 Profile in der "\
                                          "Referenzprofil-Datenbank."
        iface['cmp_combined_lr'] = "Combined LR:"
        iface['cmp_log10_lr'] = "log₁₀ LR:"
        iface['cmp_conclusion'] = "Schlussfolgerung:"
        iface['cmp_loci_stat'] = "Typisierte Loci: {n}   Ausgeschlossen: {m}"
        iface['cmp_only_in_1'] = "Nur in Profil 1:"
        iface['cmp_only_in_2'] = "Nur in Profil 2:"
        iface['cmp_contradicting'] = "Widersprüchliche Loci: {n}"
        iface['cmp_export_pdf'] = "PDF exportieren"
        iface['cmp_save_pdf'] = "Vergleichsbericht PDF speichern"
        iface['cmp_export_csv'] = "CSV exportieren"
        iface['cmp_save_csv'] = "Vergleichs-CSV speichern"
        iface['cmp_import_codis'] = "CODIS XML importieren."
        iface['cmp_codis_imported'] = "{n} Profil(e) importiert."
    elif "zh" in lang:  # Покрывает zh_CN, zh_TW, zh_HK. Можно уточнить до "zh_CN" при необходимости
        iface['ch_inact_msg'] = "未启用通道 "
        iface['aboutbtn'] = "关于 "
        iface['infoboxtxt'] = "FragalyseQt 版本 0.5.4，代号 \"Southern\"。\n\n" \
                              "本版本支持最多 8 个荧光通道的同步分析、选择性隐藏通道、支持非拉丁字符的运行名称，并能正确处理损坏的文件。" \
                              "支持将任意 *.FSA/*.HID 文件的通道名称、峰位置、峰面积、峰大小及 FWHM 导出为 CSV 格式，" \
                              "并支持导出 ABI 3500 和 SeqStudio 系列仪器生成的 *.FSA/*.HID 文件的内部分析数据。" \
                              "同时支持读取 Nanophore-05 原生 .frf 文件（高度实验性）。" \
                              "自 0.5 版起，支持使用 GeneMapper、GeneMarker 和 NCBI OSIRIS LadderInfo 面板文件进行等位基因分型（binning）。" \
                              "加载包含 stutter 比率数据的面板（GeneMapper Stutter 文件或 GeneMarker 面板）时，将自动应用 stutter 峰过滤。" \
                              "注：NCBI OSIRIS 面板不含 stutter 比率数据，因此不支持 stutter 过滤。" \
                              "同时支持导出 CODIS 3.2 CMF XML 格式（Ctrl+Shift+C）：选择样本、指定类别和实验室元数据后，" \
                              "FragalyseQt 将生成符合规范的 CODISImportFile 以供提交。\n\n" \
                              "峰面积按高斯峰假设计算。\n\n" \
                              "本软件采用 GNU AGPLv3 许可证。\n\n" \
                              "如需联系作者，请发送邮件至 dorif11@gmail.com "
        iface['openfragmentfile'] = "打开文件 "
        iface['exportinternal'] = "导出内部分析数据 "
        iface['csvexport'] = "导出为 CSV "
        iface['exportwholesession'] = "导出整个会话 "
        iface['choosefolder'] = "选择导出文件夹 "
        iface['unsuppeq'] = "不支持的设备！ "
        iface['unsuppeqmsg'] = "内部分析数据仅能从 ABI 3500 或 SeqStudio 系列测序仪生成的 FSA 文件中导出！ "
        iface['dmgdfile'] = "文件已损坏！ "
        iface['nodatamsg'] = "文件中无数据！ "
        iface['hidechannel'] = "隐藏通道 "
        iface['minph'] = "设置最小峰高： "
        iface['minpw'] = "设置最小峰宽： "
        iface['minpp'] = "设置最小峰突出度（Prominence）： "
        iface['minww'] = "平滑窗口半宽： "
        iface['minpkwl'] = "检测窗口宽度： "
        iface['minah'] = "最小等位基因峰高： "
        iface['minah_homo'] = "最小纯合子峰高： "
        iface['menu_view'] = "视图 "
        iface['splitview'] = "分开通道显示 "
        iface['savecsv'] = "保存 CSV "
        iface['bcd'] = "基线校正与降噪。 "
        iface['processbatch'] = "处理整个批次 "
        iface['savesession'] = "保存会话 "
        iface['opensession'] = "打开会话 "
        iface['savesessiontitle'] = "保存会话 "
        iface['opensessiontitle'] = "打开会话 "
        iface['sessionnamelabel'] = "会话名称： "
        iface['sessionverifytitle'] = "文件验证 "
        iface['sessionverifymsg'] = "一个或多个源文件缺失或已被修改。\n会话将以只读模式打开，使用数据库中存储的数据。 "
        iface['openreadonly'] = "仅以只读方式打开 "
        iface['nosessions'] = "未找到已保存的会话。 "
        iface['readonlyplot'] = "只读模式 — 源文件不可用 "
        iface['wrongsizing'] = "内标或定长方法错误！请尝试其他选项！ "
        iface['closetab'] = "关闭标签页 "
        iface['loadpanel'] = "加载面板 "
        iface['nopanel'] = "未加载面板 "
        iface['allele_col'] = "等位基因 "
        iface['loadpaneldlg'] = "加载面板文件 "
        iface['loadbinsdlg'] = "选择 bins（分型区间）文件 "
        iface['nobinsmsg'] = "未找到或选择 bins 文件。\n将仅使用等位基因范围进行注释 — 具体等位基因编号将不可用。 "
        iface['loadstutterdlg'] = "选择 stutter 比率文件 "
        iface['codisexport'] = "导出 CODIS XML "
        iface['soapapimenu'] = "SOAP API "
        iface['freq_tables_menu'] = "频率表 "
        iface['ref_profiles_menu'] = "参考图谱 "
        iface['importfreqtable'] = "导入频率表 "
        iface['importpanel'] = "导入面板至库 "
        iface['panelimported'] = "面板已保存至库。 "
        iface['codisdlgtitle'] = "导出 CODIS 3.2 CMF "
        iface['codisdestori'] = "目标 ORI： "
        iface['codissourcelab'] = "源实验室 ID： "
        iface['codisanalyst'] = "提交用户 ID： "
        iface['codisbatch'] = "批次 ID（可选）： "
        iface['codiskit'] = "试剂盒（可选）： "
        iface['codisdt'] = "提交日期/时间： "
        iface['codisspecimens'] = "样本： "
        iface['codisfile'] = "文件 "
        iface['codisspecimenid'] = "样本 ID "
        iface['codiscategory'] = "类别 "
        iface['codiscmftitle'] = "导出 CODIS CMF "
        iface['codisformat'] = "格式： "
        iface['codismsgid'] = "消息 ID： "
        iface['codisinstrid'] = "仪器 ID： "
        iface['codismanuf'] = "制造商： "
        iface['codismodel'] = "型号： "
        iface['codissoftver'] = "软件版本： "
        iface['codisuniqueevent'] = "唯一事件 ID "
        iface['codisfingerprintdt'] = "指纹采集日期/时间 "
        iface['codisarrestoffense'] = "逮捕罪名 "
        iface['codisrapidvalidation'] = "Rapid Import 需要：目标 ORI、来源 ORI、" \
                                        "消息创建者用户 ID、消息日期/时间、消息 ID " \
                                        "和仪器 ID，以及每个样本的：唯一事件 ID、" \
                                        "指纹采集日期/时间和逮捕罪名。 "
        iface['codisnopanel'] = "\u26a0 部分标签页未加载面板 — 这些样本的基因座数据将缺失。 "
        iface['codisnosize'] = "\u26a0 部分标签页无已定长（sized）的峰 — 这些样本的基因座数据将缺失。 "
        iface['codisvalidation'] = "请填写：目标 ORI、源实验室 ID、提交用户 ID 及日期/时间。 "
        iface['codisemptyid'] = "所选行的样本 ID 为空。 "
        iface['codisnorows'] = "未选择任何样本进行导出。 "
        iface['codissave'] = "保存 CODIS XML "
        iface['menu_file'] = "文件 "
        iface['menu_settings'] = "设置 "
        iface['menu_help'] = "帮助 "
        iface['addsizestd'] = "添加内标 "
        iface['stdname'] = "标准名称： "
        iface['stdchannel'] = "ILS 通道（ABIF 键）： "
        iface['stdsizes'] = "片段大小（空格分隔）： "
        iface['stdimportxml'] = "从文件导入 "
        iface['stdimporterr'] = "无法从文件中解析内标数据。 "
        iface['stdadded'] = "内标添加成功 "
        iface['menu_analysis'] = "分析 "
        iface['compare_profiles'] = "比较图谱 "
        iface['search_profile'] = "在数据库中搜索 "
        iface['search_profile_dlg'] = "在数据库中搜索图谱 "
        iface['search_profile_no_match'] = "未找到匹配的图谱。 "
        iface['search_profile_exact'] = "完全匹配 "
        iface['search_profile_partial'] = "部分匹配 "
        iface['search_profile_col_name'] = "名称"
        iface['search_profile_col_role'] = "角色"
        iface['search_profile_col_match'] = "匹配 / 共有"
        iface['search_profile_col_status'] = "状态"
        iface['search_profile_query'] = "查询图谱："
        iface['search_profile_nothing_to_search'] = "没有可用于搜索的已保存图谱。请先打开文件或保存图谱。"
        iface['save_profile'] = "保存图谱至数据库 "
        iface['save_profile_dlg'] = "保存图谱 "
        iface['save_profile_name'] = "名称： "
        iface['save_profile_role'] = "角色： "
        iface['save_profile_notes'] = "备注（可选）： "
        iface['save_profile_saved'] = "图谱已保存至数据库。 "
        iface['save_profile_empty'] = "未检测到等位基因。请先加载面板并运行分析。 "
        iface['save_profile_db'] = "数据库： "
        iface['save_profile_db_casework'] = "案件样本 "
        iface['save_profile_db_refprofiles'] = "参考图谱 "
        iface['cmp_title'] = "图谱比较 "
        iface['cmp_prof1'] = "图谱 1： "
        iface['cmp_prof2'] = "图谱 2： "
        iface['cmp_freqtable'] = "频率表： "
        iface['cmp_import_csv'] = "导入 CSV. "
        iface['cmp_theta'] = "θ (FST)： "
        iface['cmp_identity'] = "同一性 "
        iface['cmp_kinship'] = "亲缘关系 "
        iface['cmp_relationship'] = "关系类型： "
        iface['cmp_calculate'] = "计算 "
        iface['cmp_no_table'] = "未加载频率表。请先导入 CSV 文件。 "
        iface['cmp_no_tabs'] = "请至少打开 2 个文件进行比较。 "
        iface['cmp_nothing_to_compare'] = "暂无可比较的内容。请打开文件，"\
                                          "或在参考图谱数据库中至少保存 "\
                                          "2 个图谱。"
        iface['cmp_combined_lr'] = "综合似然比 (LR)： "
        iface['cmp_log10_lr'] = "log₁₀ LR： "
        iface['cmp_conclusion'] = "结论： "
        iface['cmp_loci_stat'] = "已分型基因座数：{n}   排除基因座数：{m} "
        iface['cmp_only_in_1'] = "仅在图谱 1 中："
        iface['cmp_only_in_2'] = "仅在图谱 2 中："
        iface['cmp_contradicting'] = "矛盾基因座数：{n}"
        iface['cmp_export_pdf'] = "导出 PDF "
        iface['cmp_save_pdf'] = "保存比较报告 PDF "
        iface['cmp_export_csv'] = "导出 CSV "
        iface['cmp_save_csv'] = "保存比较 CSV "
        iface['cmp_import_codis'] = "导入 CODIS XML. "
        iface['cmp_codis_imported'] = "已导入 {n} 个图谱。 "
