# This file is part of FragalyseQt.
#
# FragalyseQt is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# FragalyseQt is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with FragalyseQt. If not, see <https://www.gnu.org/licenses/>.

def localizefq(iface):
    from os import name, getenv
    if name == 'posix':
        lang = getenv('LANG')
    elif name == 'nt':
        from locale import windows_locale
        from ctypes import windll
        lang = windows_locale[windll.kernel32.GetUserDefaultUILanguage()]
    else:
        lang = "en"
# Some systems may have C or POSIX locale or no locale set.
    if lang is None or any(token in lang for token in ("en", "C.UTF-8", "POSIX")):
        iface['ch_inact_msg'] = "Inactive channel"
        iface['aboutbtn'] = "About"
        iface['infoboxtxt'] = "FragalyseQt version 0.5.3, codename \"Southern"\
                              "\".\n\nThis program version supports "\
                              "analysis of up to 8 different fluorescense "\
                              "channels simultaneously, selective channel "\
                              "hiding, non-Latin run names and can correctly"\
                              " handle damaged files, exporting peaks "\
                              "locations, areas, sizes, FWHM's and channel "\
                              "names in CSV for any *.FSA/*.HID files and "\
                              "export in CSV internal analysis data for "\
                              "*.FSA/*.HID files generated by ABI 3500 and "\
                              "SeqStudio series equipment. Also supports "\
                              "reading native Nanophore-05 .frf files "\
                              "(highly experimental). Since version 0.5, "\
                              "allele binning using GeneMapper, GeneMarker"\
                              " and NCBI OSIRIS LadderInfo panel files is"\
                              " supported. When a panel with stutter ratio"\
                              " data is loaded (GeneMapper Stutter files or"\
                              " GeneMarker panels), stutter peak filtering is"\
                              " applied automatically. Note: NCBI OSIRIS"\
                              " panels do not carry stutter ratio data —"\
                              " stutter filtering is not available for them."\
                              " Export to CODIS 3.2 CMF XML format is also "\
                              "supported (Ctrl+Shift+C): select samples, "\
                              "assign specimen categories and lab metadata, "\
                              "and FragalyseQt will generate a schema-valid"\
                              " CODISImportFile ready for submission.\n\n"\
                              "Peaks areas are calculated assuming they are "\
                              "Gaussian.\n\nGNU AGPL version 3 licensed.\n\n"\
                              "If you wish to contact the author for any"\
                              " reason - please write at dorif11@gmail.com"
        iface['openfragmentfile'] = "Open file"
        iface['exportinternal'] = "Export Internal Analysis Data"
        iface['csvexport'] = "Export in CSV"
        iface['exportwholesession'] = "Export whole session"
        iface['choosefolder'] = "Choose export folder"
        iface['unsuppeq'] = "Unsupported equipment!"
        iface['unsuppeqmsg'] = "Internal analysis data could be exported only"\
                               " from FSA files generated by ABI 3500 and "\
                               "SeqStudio family sequencers!"
        iface['dmgdfile'] = "Damaged file!"
        iface['nodatamsg'] = "There are no data in file!"
        iface['hidechannel'] = "Hide "
        iface['minph'] = "Select minimal peak height:"
        iface['minpw'] = "Select minimal peak width:"
        iface['minpp'] = "Select minimal peak prominence:"
        iface['minww'] = "Select minimal window width:"
        iface['minah'] = "Min. allele height:"
        iface['menu_view'] = "View"
        iface['splitview'] = "Split channels"
        iface['savecsv'] = "Save CSV"
        iface['bcd'] = "Baseline correction and denoising."
        iface['processbatch'] = "Process whole batch"
        iface['savesession'] = "Save Session"
        iface['opensession'] = "Open Session"
        iface['savesessiontitle'] = "Save Session"
        iface['opensessiontitle'] = "Open Session"
        iface['sessionnamelabel'] = "Session name:"
        iface['sessionverifytitle'] = "File Verification"
        iface['sessionverifymsg'] = ("One or more source files are missing or "
                                     "have been modified.\nThe session will open "
                                     "in read-only mode using data stored in the "
                                     "database.")
        iface['openreadonly'] = "Open read-only"
        iface['nosessions'] = "No saved sessions found."
        iface['readonlyplot'] = "Read-only — source file unavailable"
        iface['wrongsizing'] = "Wrong ladder or sizing method! Please, try "\
                               "another ones!"
        iface['closetab'] = "Close Tab"
        iface['loadpanel'] = "Load Panel"
        iface['nopanel'] = "No panel loaded"
        iface['allele_col'] = "Allele"
        iface['loadpaneldlg'] = "Load panel file"
        iface['loadbinsdlg'] = "Select companion bins file"
        iface['nobinsmsg'] = "No bins file was found or selected. "\
                             "Only marker ranges will be used for "\
                             "annotation — specific allele numbers "\
                             "will not be available."
        iface['loadstutterdlg'] = "Select stutter ratios file"
        iface['codisexport'] = "Export CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Import Panel to Library"
        iface['panelimported'] = "Panel(s) saved to library."
        iface['codisdlgtitle'] = "CODIS 3.2 CMF Export"
        iface['codisdestori'] = "Destination ORI:"
        iface['codissourcelab'] = "Source Lab ID:"
        iface['codisanalyst'] = "Submit User ID:"
        iface['codisbatch'] = "Batch ID (optional):"
        iface['codiskit'] = "Kit (optional):"
        iface['codisdt'] = "Submit date/time:"
        iface['codisspecimens'] = "Specimens:"
        iface['codisfile'] = "File"
        iface['codisspecimenid'] = "Specimen ID"
        iface['codiscategory'] = "Category"

        iface['codisnopanel'] = "\u26a0 Some tabs have no panel loaded — "\
                                "locus data will be absent for those specimens."
        iface['codisnosize'] = "\u26a0 Some tabs have no sized peaks — "\
                               "locus data will be absent for those specimens."
        iface['codisvalidation'] = "Please fill in: Destination ORI, Source "\
                                   "Lab ID, Submit User ID and date/time."
        iface['codisemptyid'] = "Specimen ID is empty for a selected row."
        iface['codisnorows'] = "No specimens selected for export."
        iface['codissave'] = "Save CODIS XML"
        iface['menu_file'] = "File"
        iface['menu_settings'] = "Settings"
        iface['menu_help'] = "Help"
        iface['addsizestd'] = "Add size standard"
        iface['stdname'] = "Standard Name:"
        iface['stdchannel'] = "ILS Channel (ABIF key):"
        iface['stdsizes'] = "Sizes (space separated):"
        iface['stdadded'] = "Size standard added successfully"
    elif "ru" in lang:
        iface['ch_inact_msg'] = "Неактивный канал"
        iface['aboutbtn'] = "О программе"
        iface['infoboxtxt'] = "FragalyseQt версия 0.5.3, кодовое имя "\
                              "\"Саузерн\".\n\nЭта версия программы "\
                              "поддерживает одновременный анализ до 8 каналов"\
                              " флуоресценции, избирательное сокрытие каналов"\
                              ", не-латинские имена запусков, может правильно"\
                              " работать с повреждёнными файлами, "\
                              "поддерживает экспорт имён каналов, положений, "\
                              "площадей, размеров и FWHM пиков в формат CSV "\
                              "для любого файла *.FSA/*.HID и экспорт данных"\
                              " внутреннего анализа данных для файлов "\
                              "*.FSA/*.HID, полученных на инструментах ABI "\
                              "3500 и SeqStudio. Также поддерживается чтение"\
                              " нативных файлов Нанофор-05 .frf (крайне "\
                              "экспериментально). Начиная с версии 0.5, "\
                              "поддерживается аллельное бинирование с "\
                              "использованием файлов панелей GeneMapper, "\
                              "GeneMarker и NCBI OSIRIS LadderInfo. При "\
                              "загрузке панели с данными о коэффициентах "\
                              "статтера (файлы GeneMapper Stutter или панели "\
                              "GeneMarker) автоматически применяется "\
                              "фильтрация статтер-пиков. Примечание: панели "\
                              "NCBI OSIRIS не содержат данных о коэффициентах"\
                              " статтера — фильтрация статтера для них "\
                              "недоступна. Также поддерживается экспорт в "\
                              "формат CODIS 3.2 CMF XML (Ctrl+Shift+C): "\
                              "выберите образцы, назначьте категории и "\
                              "метаданные лаборатории — и FragalyseQt "\
                              "сформирует валидный CODISImportFile, готовый"\
                              " к загрузке в базу данных.\n\nПлощади пиков "\
                              "рассчитываются исходя из того, что пики "\
                              "являются гауссовыми.\n\nЛицензировано под "\
                              "GNU AGPL версии 3.\n\nЕсли по какой-либо "\
                              "причине вы хотите проконтактировать с автором"\
                              " - пишите, пожалуйста, на dorif11@gmail.com"
        iface['openfragmentfile'] = "Открыть файл"
        iface['exportinternal'] = "Экспорт Данных Внутреннего Анализа"
        iface['csvexport'] = "Экспорт в CSV"
        iface['exportwholesession'] = "Экспортировать всю сессию"
        iface['choosefolder'] = "Выберите папку для экспорта"
        iface['unsuppeq'] = "Неподдерживаемое оборудование!"
        iface['unsuppeqmsg'] = "Данные внутреннего анализа могут быть "\
                               "экспортированы только из файлов FSA, "\
                               "полученных на ABI 3500 или семействе "\
                               "SeqStudio!"
        iface['dmgdfile'] = "Повреждённый файл!"
        iface['nodatamsg'] = "В файле отсутствуют данные!"
        iface['hidechannel'] = "Скрыть "
        iface['minph'] = "Выберите минимальную высоту пика:"
        iface['minpw'] = "Выберите минимальную ширину пика:"
        iface['minpp'] = "Выберите минимальное возвышение пика:"
        iface['minww'] = "Выберите минимальную ширину окна:"
        iface['minah'] = "Мин. высота аллеля:"
        iface['menu_view'] = "Вид"
        iface['splitview'] = "Разделить каналы"
        iface['savecsv'] = "Сохранить CSV"
        iface['bcd'] = "Коррекция базовой линии и шумоподавление."
        iface['processbatch'] = "Обработать весь пакет"
        iface['savesession'] = "Сохранить сессию"
        iface['opensession'] = "Открыть сессию"
        iface['savesessiontitle'] = "Сохранить сессию"
        iface['opensessiontitle'] = "Открыть сессию"
        iface['sessionnamelabel'] = "Название сессии:"
        iface['sessionverifytitle'] = "Проверка файлов"
        iface['sessionverifymsg'] = ("Один или несколько исходных файлов "
                                     "отсутствуют или были изменены.\nСессия "
                                     "будет открыта в режиме только для чтения "
                                     "с данными из базы данных.")
        iface['openreadonly'] = "Открыть только для чтения"
        iface['nosessions'] = "Сохранённые сессии не найдены."
        iface['readonlyplot'] = "Только чтение — исходный файл недоступен"
        iface['wrongsizing'] = "Ошибочный размерный маркер или метод "\
                               "определения размера! Пожалуйста, "\
                               "попробуйте другие!"
        iface['closetab'] = "Закрыть вкладку"
        iface['loadpanel'] = "Загрузить панель"
        iface['nopanel'] = "Панель не загружена"
        iface['allele_col'] = "Аллель"
        iface['loadpaneldlg'] = "Загрузить файл панели"
        iface['loadbinsdlg'] = "Выберите файл бинов"
        iface['nobinsmsg'] = "Файл бинов не найден и не выбран. "\
                             "Для аннотации будут использоваться диапазоны "\
                             "аллелей — конкретные номера аллелей "\
                             "будут недоступны."
        iface['loadstutterdlg'] = "Выберите файл коэффициентов статтера"
        iface['codisexport'] = "Экспорт CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Импортировать панель в библиотеку"
        iface['panelimported'] = "Панель(и) сохранены в библиотеку."
        iface['codisdlgtitle'] = "Экспорт CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI назначения:"
        iface['codissourcelab'] = "ID лаборатории-источника:"
        iface['codisanalyst'] = "ID пользователя:"
        iface['codisbatch'] = "ID партии (необяз.):"
        iface['codiskit'] = "Набор (необяз.):"
        iface['codisdt'] = "Дата/время подачи:"
        iface['codisspecimens'] = "Образцы:"
        iface['codisfile'] = "Файл"
        iface['codisspecimenid'] = "ID образца"
        iface['codiscategory'] = "Категория"
        iface['codisnopanel'] = "\u26a0 В некоторых вкладках не загружена панель — "\
                                "данные локусов будут отсутствовать для этих образцов."
        iface['codisnosize'] = "\u26a0 В некоторых вкладках нет пиков с размером — "\
                               "данные локусов будут отсутствовать для этих образцов."
        iface['codisvalidation'] = "Пожалуйста, заполните: ORI назначения, "\
                                   "ID лаборатории, ID пользователя и"\
                                   " дату/время."
        iface['codisemptyid'] = "ID образца не заполнен для одной из "\
                                "выбранных строк."
        iface['codisnorows'] = "Не выбрано ни одного образца для экспорта."
        iface['codissave'] = "Сохранить CODIS XML"
        iface['menu_file'] = "Файл"
        iface['menu_settings'] = "Настройки"
        iface['menu_help'] = "Справка"
        iface['addsizestd'] = "Добавить размерный стандарт"
        iface['stdname'] = "Имя стандарта:"
        iface['stdchannel'] = "Канал ILS (ключ ABIF):"
        iface['stdsizes'] = "Размеры (через пробел):"
        iface['stdadded'] = "Размерный стандарт успешно добавлен"
    elif "ua" in lang:
        iface['ch_inact_msg'] = "Неактивний канал"
        iface['aboutbtn'] = "О програмі"
        iface['infoboxtxt'] = "FragalyseQt версія 0.5.3, кодове ім'я "\
                              "\"Саузерн\".\n\n Версія програми підтримує "\
                              "одночасний аналіз до 8 каналів флуоресценции, "\
                              "вибіркове приховування каналів, не-латинські "\
                              "імена запусків, може правильно працювати з "\
                              "пошкодженими файлами, підтримує експорт імен "\
                              "каналів, положень, площадей, розміру і FWHM "\
                              "піков у формат CSV для будь-якого файла"\
                              " *.FSA/*.HID та експорт даних внутрішнього "\
                              "аналізу даних для файлів *.FSA/*.HID, "\
                              "отриманих на інструментах ABI 3500 и "\
                              "SeqStudio. Також підтримується читання "\
                              "нативних файлів Нанофор-05 .frf (вкрай "\
                              "експериментально). Починаючи з версії 0.5, "\
                              "підтримується алельне бінування з "\
                              "використанням файлів панелей GeneMapper, "\
                              "GeneMarker та NCBI OSIRIS LadderInfo. При "\
                              "завантаженні панелі з даними про коефіцієнти "\
                              "статтера (файли GeneMapper Stutter або панелі "\
                              "GeneMarker) автоматично застосовується "\
                              "фільтрація статтер-піків. Примітка: панелі "\
                              "NCBI OSIRIS не містять даних про коефіцієнти "\
                              "статтера — фільтрація статтера для них "\
                              "недоступна. Також підтримується експорт у "\
                              "формат CODIS 3.2 CMF XML (Ctrl+Shift+C): "\
                              "оберіть зразки, призначте категорії та "\
                              "метадані лабораторії — і FragalyseQt "\
                              "сформує валідний CODISImportFile, готовий"\
                              " до завантаження в базу даних."\
                              "\n\nПлощаді піков розраховуються "\
                              "виходячи з того, що піки є гауссовими.\n\n"\
                              "Ліцензовано під GNU AGPL версії 3.\n\nЯкщо з "\
                              "будь-якої причини ви хочете проконтактувати з "\
                              "автором - пишіть, будь ласка, на "\
                              "dorif11@gmail.com"
        iface['openfragmentfile'] = "Відкрити файл"
        iface['exportinternal'] = "Експорт Даних Внутренього Аналіза"
        iface['csvexport'] = "Експорт в CSV"
        iface['exportwholesession'] = "Експортувати всю сесію"
        iface['choosefolder'] = "Виберіть папку для експорту"
        iface['unsuppeq'] = "Непідтримуване оболаднення!"
        iface['unsuppeqmsg'] = "Дані внутренього аналіза можуть бути "\
                               "експортовані тільки із файлів FSA, отриманих"\
                               " на ABI 3500 або сімействі SeqStudio!"
        iface['dmgdfile'] = "Пошкоджений файл!"
        iface['nodatamsg'] = "У файлі відсутні дані!"
        iface['hidechannel'] = "Сховати "
        iface['minph'] = "Виберіть мінімальну висоту піку:"
        iface['minpw'] = "Виберіть мінімальну ширину піку:"
        iface['minpp'] = "Виберіть мінімальне підвищення піку:"
        iface['minww'] = "Виберіть мінімальну ширину вікна:"
        iface['minah'] = "Мін. висота алеля:"
        iface['menu_view'] = "Вигляд"
        iface['splitview'] = "Розділити канали"
        iface['savecsv'] = "Зберегти CSV"
        iface['bcd'] = "Корекція базової лінії та шумозаглушення."
        iface['processbatch'] = "Обробити весь пакет"
        iface['savesession'] = "Зберегти сесію"
        iface['opensession'] = "Відкрити сесію"
        iface['savesessiontitle'] = "Зберегти сесію"
        iface['opensessiontitle'] = "Відкрити сесію"
        iface['sessionnamelabel'] = "Назва сесії:"
        iface['sessionverifytitle'] = "Перевірка файлів"
        iface['sessionverifymsg'] = ("Один або кілька вихідних файлів "
                                     "відсутні або були змінені.\nСесія буде "
                                     "відкрита у режимі лише для читання з "
                                     "даними з бази даних.")
        iface['openreadonly'] = "Відкрити лише для читання"
        iface['nosessions'] = "Збережених сесій не знайдено."
        iface['readonlyplot'] = "Лише читання — вихідний файл недоступний"
        iface['wrongsizing'] = "Помилковий розмірний маркер чи метод "\
                               "визначення розміру! Будь ласка, спробуйте"\
                               " інші!"
        iface['closetab'] = "Закрити вкладку"
        iface['loadpanel'] = "Завантажити панель"
        iface['nopanel'] = "Панель не завантажена"
        iface['allele_col'] = "Алель"
        iface['loadpaneldlg'] = "Завантажити файл панелі"
        iface['loadbinsdlg'] = "Виберіть файл бінів"
        iface['nobinsmsg'] = "Файл бінів не знайдено і не вибрано. Для "\
                             "анотації будуть використовуватися діапазони "\
                             "алелів — конкретні номери алелів "\
                             "будуть недоступні."
        iface['loadstutterdlg'] = "Виберіть файл коефіцієнтів статера"
        iface['codisexport'] = "Експорт CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Імпортувати панель до бібліотеки"
        iface['panelimported'] = "Панель(і) збережено до бібліотеки."
        iface['codisdlgtitle'] = "Експорт CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI призначення:"
        iface['codissourcelab'] = "ID лабораторії-джерела:"
        iface['codisanalyst'] = "ID користувача:"
        iface['codisbatch'] = "ID партії (необов.):"
        iface['codiskit'] = "Набір (необов.):"
        iface['codisdt'] = "Дата/час подачі:"
        iface['codisspecimens'] = "Зразки:"
        iface['codisfile'] = "Файл"
        iface['codisspecimenid'] = "ID зразка"
        iface['codiscategory'] = "Категорія"
        iface['codisnopanel'] = "\u26a0 У деяких вкладках не завантажено панель — "\
                                "дані локусів будуть відсутні для цих зразків."
        iface['codisnosize'] = "\u26a0 У деяких вкладках немає піків з розміром — "\
                               "дані локусів будуть відсутні для цих зразків."
        iface['codisvalidation'] = "Будь ласка, заповніть: ORI призначення, "\
                                   "ID лабораторії, ID користувача та дату/час."
        iface['codisemptyid'] = "ID зразка не заповнений для одного з вибраних"\
                                " рядків."
        iface['codisnorows'] = "Жодного зразка не вибрано для експорту."
        iface['codissave'] = "Зберегти CODIS XML"
        iface['menu_file'] = "Файл"
        iface['menu_settings'] = "Налаштування"
        iface['menu_help'] = "Довідка"
        iface['addsizestd'] = "Додати розмірний стандарт"
        iface['stdname'] = "Ім'я стандарту:"
        iface['stdchannel'] = "Канал ILS (ключ ABIF):"
        iface['stdsizes'] = "Розміри (через пробіл):"
        iface['stdadded'] = "Розмірний стандарт успішно додано"
    elif "ro" in lang:
        iface['ch_inact_msg'] = "Canal inactiv"
        iface['aboutbtn'] = "Despre program"
        iface['infoboxtxt'] = "FragalyseQt versiune 0.5.3, codename "\
                              "\"Southern\".\n\nAceastă versiune permite "\
                              "analiza simultană a pînă la 8 canale de "\
                              "fluorescență, ascunderea selectivă a canalelor"\
                              ", nume non-latine a runurilor, poate funcționa"\
                              " corect cu fișiere deteriorate, permite "\
                              "exportarea numelor de canale, locațiile, "\
                              "suprafețele, dimensiunile și FWHMurile a "\
                              "vîrfurilor în formatul CSV, pentru orice "\
                              "fișierul de tip *.FSA/*.HID și exportarea în "\
                              "formatul CSV a datelor analizei interne "\
                              "pentru fișiere de tip *.FSA/*.HID generate de "\
                              "echipamentele de model ABI 3500 și SeqStudio."\
                              "De asemenea, sunt acceptate fișierele native "\
                              "Nanophore-05 .frf (foarte experimental). "\
                              "Începând cu versiunea 0.5, este acceptată "\
                              "binarizarea alelelor folosind fișiere de panou"\
                              " GeneMapper, GeneMarker și NCBI OSIRIS"\
                              " LadderInfo. Când se încarcă un panou cu date"\
                              " privind ratele stutter (fișiere GeneMapper"\
                              " Stutter sau panouri GeneMarker), filtrarea"\
                              " vîrfurilor stutter se aplică automat. Notă:"\
                              " panourile NCBI OSIRIS nu conțin date privind"\
                              " ratele stutter — filtrarea stutter nu este"\
                              " disponibilă pentru acestea. De asemenea, este"\
                              " acceptat exportul în formatul CODIS 3.2 CMF "\
                              "XML (Ctrl+Shift+C): selectați probe, atribuiți"\
                              " categorii și metadate de laborator, iar "\
                              "FragalyseQt va genera un CODISImportFile valid"\
                              " pentru încărcare în baza de date.\n\n"\
                              "Suprafețele vîrfurilor, sunt calculate "\
                              "presupunînd că vîrfurile sunt gausiene.\n\n"\
                              "Licențiat sub GNU AGPL versiunea 3.\n\nDacă "\
                              "doriți să contactați autorul, pentru orice "\
                              "întrebare - scrieți, vă rog, la adresa "\
                              "dorif11@gmail.com"
        iface['openfragmentfile'] = "Deschideți fișierul"
        iface['exportinternal'] = "Exportul Datelor Analizei Interne"
        iface['csvexport'] = "Exportul în CSV"
        iface['exportwholesession'] = "Exportă întreaga sesiune"
        iface['choosefolder'] = "Alegeți folderul de export"
        iface['unsuppeq'] = "Echipament nesusținut!"
        iface['unsuppeqmsg'] = "Datele analizei interne pot fi exportate "\
                               "numai pentru fișierile FSA generate de "\
                               "echipamentele de model ABI 3500 și SeqStudio!"
        iface['dmgdfile'] = "Fișier deteriorat!"
        iface['nodatamsg'] = "In fișier lipsesc datele!"
        iface['hidechannel'] = "Ascunde "
        iface['minph'] = "Selectaţi înălţimea minimală a vîrfului:"
        iface['minpw'] = "Selectaţi lăţimea minimală a vîrfului:"
        iface['minpp'] = "Selectaţi proeminenţa minimală a vîrfului:"
        iface['minww'] = "Selectaţi lăţimea minimală a ferestrei:"
        iface['minah'] = "Înălţ. min. alele:"
        iface['menu_view'] = "Vizualizare"
        iface['splitview'] = "Canale separate"
        iface['savecsv'] = "Salvează CSV"
        iface['bcd'] = "Corectarea liniei de bază și supresia zgomotului."
        iface['processbatch'] = "Procesează tot lotul"
        iface['savesession'] = "Salvează sesiunea"
        iface['opensession'] = "Deschide sesiunea"
        iface['savesessiontitle'] = "Salvează sesiunea"
        iface['opensessiontitle'] = "Deschide sesiunea"
        iface['sessionnamelabel'] = "Numele sesiunii:"
        iface['sessionverifytitle'] = "Verificarea fișierelor"
        iface['sessionverifymsg'] = ("Unul sau mai multe fișiere sursă lipsesc "
                                     "sau au fost modificate.\nSesiunea va fi "
                                     "deschisă în modul doar citire cu datele "
                                     "din baza de date.")
        iface['openreadonly'] = "Deschide doar citire"
        iface['nosessions'] = "Nu s-au găsit sesiuni salvate."
        iface['readonlyplot'] = "Doar citire — fișierul sursă indisponibil"
        iface['wrongsizing'] = "Marker de dimensiuni sau metodă de "\
                               "dimensionare incorectă! Vă rugăm să"\
                               " încercați altele!"
        iface['closetab'] = "Închide fila"
        iface['loadpanel'] = "Încărcați panoul"
        iface['nopanel'] = "Niciun panou încărcat"
        iface['allele_col'] = "Alelă"
        iface['loadpaneldlg'] = "Încărcați fișierul panoului"
        iface['loadbinsdlg'] = "Selectați fișierul bins"
        iface['nobinsmsg'] = "Niciun fișier bins nu a fost găsit sau "\
                             "selectat. Pentru adnotare vor fi utilizate "\
                             "intervalele de alele — numerele specifice "\
                             "ale alelelor nu vor fi disponibile."
        iface['loadstutterdlg'] = "Selectați fișierul raporturilor stutter"
        iface['codisexport'] = "Export CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Importați panoul în bibliotecă"
        iface['panelimported'] = "Panoul(ele) salvat(e) în bibliotecă."
        iface['codisdlgtitle'] = "Export CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI destinație:"
        iface['codissourcelab'] = "ID laborator sursă:"
        iface['codisanalyst'] = "ID utilizator:"
        iface['codisbatch'] = "ID lot (opț.):"
        iface['codiskit'] = "Kit (opț.):"
        iface['codisdt'] = "Dată/oră depunere:"
        iface['codisspecimens'] = "Specimene:"
        iface['codisfile'] = "Fișier"
        iface['codisspecimenid'] = "ID specimen"
        iface['codiscategory'] = "Categorie"

        iface['codisnopanel'] = "\u26a0 Unele file nu au panou încărcat "\
                                "\u2014 datele locusurilor vor fi absente."
        iface['codisnosize'] = "\u26a0 Unele file nu au vîrfuri cu dimensiune"\
                               " \u2014 datele locusurilor vor fi absente."
        iface['codisvalidation'] = "Completați: ORI destinație, "\
                                   "ID laborator, D utilizator și dată/oră."
        iface['codisemptyid'] = "ID specimen este gol pentru un rând selectat."
        iface['codisnorows'] = "Niciun specimen selectat pentru export."
        iface['codissave'] = "Salvare CODIS XML"
        iface['menu_file'] = "Fișier"
        iface['menu_settings'] = "Setări"
        iface['menu_help'] = "Ajutor"
        iface['addsizestd'] = "Adăugați standardul de mărime"
        iface['stdname'] = "Nume standard:"
        iface['stdchannel'] = "Canal ILS (cheia ABIF):"
        iface['stdsizes'] = "Dimensiuni (separate prin spațiu):"
        iface['stdadded'] = "Standardul de mărime a fost adăugat cu succes"
    elif "fr" in lang:
        iface['ch_inact_msg'] = "Canal inactif"
        iface['aboutbtn'] = "Au sujet de"
        iface['infoboxtxt'] = "FragalyseQt version 0.5.3, alias "\
                              "\"Southern\".\n\nCette version du programme "\
                              "prend en charge l'analyse simultanée de "\
                              "jusqu'à 8 canaux de fluorescence différents, "\
                              "le masquage sélectif des canaux, les noms "\
                              "d'exécution non latins et peut gérer "\
                              "correctement les Fichiers endommagés, exporter"\
                              " les emplacements des pics, zones, tailles, "\
                              "FWHM et noms de canal au format CSV pour tous "\
                              "les Fichiers *.FSA/*.HID et exportation au "\
                              "format CSV des données d'analyse interne pour "\
                              "les Fichiers *.FSA/*.HID générés par les "\
                              "équipements des séries ABI 3500 et SeqStudio."\
                              " Prend également en charge les fichiers natifs"\
                              " Nanophore-05 .frf (hautement expérimental)."\
                              " Depuis la version 0.5, le binnage des allèles"\
                              " à l'aide de fichiers de panneaux GeneMapper,"\
                              " GeneMarker et NCBI OSIRIS LadderInfo est pris"\
                              " en charge. Lorsqu'un panneau avec des données"\
                              " de ratios stutter est chargé (fichiers"\
                              " GeneMapper Stutter ou panneaux GeneMarker),"\
                              " le filtrage des pics stutter est appliqué"\
                              " automatiquement. Note : les panneaux NCBI "\
                              "OSIRIS ne contiennent pas de données de ratios"\
                              " stutter — le filtrage stutter n'est pas"\
                              " disponible pour eux. L'export au"\
                              " format CODIS 3.2 CMF XML est également"\
                              " disponible (Ctrl+Shift+C) : sélectionnez les"\
                              " échantillons, attribuez les catégories et"\
                              " métadonnées du laboratoire, et FragalyseQt"\
                              " génèrera un CODISImportFile valide prêt pour"\
                              " la soumission.\n\nLes zones de pics sont"\
                              " calculées en "\
                              "supposant qu'il s'agit de pics gaussiens.\n\n"\
                              "Licence sous GNU AGPL version 3.\n\nSi vous "\
                              "souhaitez contacter l'auteur pour une raison "\
                              "quelconque, veuillez écrire à dorif11@gmail.com"
        iface['openfragmentfile'] = "Ouvrer le Fichier"
        iface['exportinternal'] = "Exporter des données d'analyse interne"
        iface['csvexport'] = "Exporter en CSV"
        iface['exportwholesession'] = "Exporter toute la session"
        iface['choosefolder'] = "Choisissez le dossier d'export"
        iface['unsuppeq'] = "L'équipement non supportés!"
        iface['unsuppeqmsg'] = "Les données d'analyse internes ne pouvaient "\
                               "être exportées qu'à partir de Fichiers FSA "\
                               "générés par les séquenceurs de la famille "\
                               "ABI 3500 et SeqStudio!"
        iface['dmgdfile'] = "Fichier endommagé!"
        iface['nodatamsg'] = "Il n'y a pas de données dans le Fichier!"
        iface['hidechannel'] = "Masquer"
        iface['minph'] = "Sélectionnez la hauteur de pic minimale:"
        iface['minpw'] = "Sélectionnez la largeur de pic minimale:"
        iface['minpp'] = "Sélectionnez la proéminence de pic minimale:"
        iface['minww'] = "Sélectionnez la largeur de la fenêtre minimale:"
        iface['minah'] = "Haut. min. allèle:"
        iface['menu_view'] = "Affichage"
        iface['splitview'] = "Canaux séparés"
        iface['savecsv'] = "Enregistrer CSV"
        iface['bcd'] = "Correction de la ligne de base et suppression du"\
                       " bruit."
        iface['processbatch'] = "Traiter tout le lot"
        iface['savesession'] = "Enregistrer la session"
        iface['opensession'] = "Ouvrir la session"
        iface['savesessiontitle'] = "Enregistrer la session"
        iface['opensessiontitle'] = "Ouvrir la session"
        iface['sessionnamelabel'] = "Nom de la session :"
        iface['sessionverifytitle'] = "Vérification des fichiers"
        iface['sessionverifymsg'] = ("Un ou plusieurs fichiers sources sont "
                                     "manquants ou ont été modifiés.\nLa session "
                                     "s'ouvrira en lecture seule avec les données "
                                     "stockées dans la base de données.")
        iface['openreadonly'] = "Ouvrir en lecture seule"
        iface['nosessions'] = "Aucune session sauvegardée trouvée."
        iface['readonlyplot'] = "Lecture seule — fichier source indisponible"
        iface['wrongsizing'] = "Marqueur de dimensionnement ou méthode de "\
                               "dimensionnement incorrect ! S'il vous plaît"\
                               ", essayez-en d'autres !"
        iface['closetab'] = "Fermer l'onglet"
        iface['loadpanel'] = "Charger le panneau"
        iface['nopanel'] = "Aucun panneau chargé"
        iface['allele_col'] = "Allèle"
        iface['loadpaneldlg'] = "Charger le fichier de panneau"
        iface['loadbinsdlg'] = "Sélectionner le fichier bins"
        iface['nobinsmsg'] = "Aucun fichier bins n'a été trouvé ou "\
                             "sélectionné. Les plages d'allèles seront "\
                             "utilisées pour l'annotation — les numéros "\
                             "d'allèles spécifiques ne seront pas disponibles."
        iface['loadstutterdlg'] = "Sélectionner le fichier de ratios stutter"
        iface['codisexport'] = "Exporter CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Importer le panneau dans la bibliothèque"
        iface['panelimported'] = "Panneau(x) enregistré(s) dans la bibliothèque."
        iface['codisdlgtitle'] = "Export CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI destinataire :"
        iface['codissourcelab'] = "ID laboratoire source :"
        iface['codisanalyst'] = "ID utilisateur :"
        iface['codisbatch'] = "ID lot (opt.) :"
        iface['codiskit'] = "Kit (opt.) :"
        iface['codisdt'] = "Date/heure dépôt :"
        iface['codisspecimens'] = "Spécimens :"
        iface['codisfile'] = "Fichier"
        iface['codisspecimenid'] = "ID spécimen"
        iface['codiscategory'] = "Catégorie"
        iface['codisnopanel'] = "\u26a0 Certains onglets n\'ont pas de panneau"\
                                " — les données de locus seront absentes."
        iface['codisnosize'] = "\u26a0 Certains onglets n\'ont pas de pics dimensionnés"\
                               " — les données de locus seront absentes."
        iface['codisvalidation'] = "Veuillez remplir : ORI destinataire, ID laboratoire,"\
                                   " ID utilisateur et date/heure."
        iface['codisemptyid'] = "L\'ID spécimen est vide pour une ligne sélectionnée."
        iface['codisnorows'] = "Aucun spécimen sélectionné pour l\'export."
        iface['codissave'] = "Enregistrer CODIS XML"
        iface['menu_file'] = "Fichier"
        iface['menu_settings'] = "Paramètres"
        iface['menu_help'] = "Aide"
        iface['addsizestd'] = "Ajouter un standard de taille"
        iface['stdname'] = "Nom du standard:"
        iface['stdchannel'] = "Canal ILS (clé ABIF):"
        iface['stdsizes'] = "Tailles (séparées par des espaces):"
        iface['stdadded'] = "Standard de taille ajouté avec succès"
    elif "bg" in lang:
        iface['ch_inact_msg'] = "Неактивен канал"
        iface['aboutbtn'] = "Относно програмата"
        iface['infoboxtxt'] = "FragalyseQt версия 0.5.3, кодово име \"Саузерн"\
                              "\".\n\nТази версия на програмата поддържа "\
                              "едновременен анализ до 8 флуоресцентни канала,"\
                              " селективно скриване на канали, не-латински "\
                              "имена на изпълнения, може да работи правилно с"\
                              " повредени файлове, поддържа експорт на имена "\
                              "на канали, позиции, площите, размери и FWHM "\
                              "пикове в CSV формат за всеки *.FSA/*.HID файл "\
                              "и експортиране на вътрешни данни за анализ на "\
                              "данни за *.FSA/*.HID файлове, получени с ABI "\
                              "3500 и инструменти SeqStudio. Поддържа се и "\
                              "четене на нативни файлове Nanophore-05 .frf "\
                              "(силно експериментално). Считано от версия "\
                              "0.5, се поддържа алелно биниране с помощта на"\
                              " файлове с панели GeneMapper, GeneMarker и"\
                              " NCBI OSIRIS LadderInfo. При зареждане на"\
                              " панел с данни за коефициенти на статер"\
                              " (GeneMapper Stutter файлове или GeneMarker"\
                              " панели) автоматично се прилага филтриране на"\
                              " статер пикове. Забележка: NCBI OSIRIS"\
                              " панелите не съдържат данни за коефициенти на"\
                              " статер — филтрирането на статер не е налично"\
                              " за тях. Поддържа се и експорт във формат"\
                              " CODIS 3.2"\
                              " CMF XML (Ctrl+Shift+C): изберете проби,"\
                              " задайте категории и метаданни на"\
                              " лабораторията — FragalyseQt ще генерира"\
                              " валиден CODISImportFile, готов за подаване."\
                              "\n\nПлощите на "\
                              "пиковете се изчисляват, като се приема, че "\
                              "пиковете са гаусови.\n\nЛицензирано под GNU "\
                              "AGPL версия 3.\n\nАко по някаква причина "\
                              "искате да се свържете с автора, моля, "\
                              "изпратете имейл на dorif11@gmail.com"
        iface['openfragmentfile'] = "Отвори файла"
        iface['exportinternal'] = "Експорт на Данни от Вътрешен Анализ"
        iface['csvexport'] = "Експорт в CSV"
        iface['exportwholesession'] = "Експортиране на цялата сесия"
        iface['choosefolder'] = "Изберете папка за експорт"
        iface['unsuppeq'] = "Неподдържан оборудване!"
        iface['unsuppeqmsg'] = "Данните за вътрешен анализ могат да бъдат "\
                               "експортирани само от файлове FSA, придобити "\
                               "на ABI 3500 или фамилията SeqStudio!"
        iface['dmgdfile'] = "Повреден файл!"
        iface['nodatamsg'] = "Във файла няма данни!"
        iface['hidechannel'] = "Крия "
        iface['minph'] = "Изберете минимална височина на върха:"
        iface['minpw'] = "Изберете минимална ширина на върха:"
        iface['minpp'] = "Изберете минимална надморска височина:"
        iface['minww'] = "Изберете минимална ширина на прозореца:"
        iface['minah'] = "Мин. вис. алел:"
        iface['menu_view'] = "Изглед"
        iface['splitview'] = "Разделени канали"
        iface['savecsv'] = "Запазване на CSV"
        iface['bcd'] = "Корекция на базовата линия и шумопотискане."
        iface['processbatch'] = "Обработка на целия пакет"
        iface['savesession'] = "Запазване на сесията"
        iface['opensession'] = "Отваряне на сесия"
        iface['savesessiontitle'] = "Запазване на сесията"
        iface['opensessiontitle'] = "Отваряне на сесия"
        iface['sessionnamelabel'] = "Име на сесията:"
        iface['sessionverifytitle'] = "Проверка на файловете"
        iface['sessionverifymsg'] = ("Един или повече изходни файлове липсват "
                                     "или са били променени.\nСесията ще се "
                                     "отвори в режим само за четене с данните "
                                     "от базата данни.")
        iface['openreadonly'] = "Отвори само за четене"
        iface['nosessions'] = "Няма запазени сесии."
        iface['readonlyplot'] = "Само четене — изходният файл е недостъпен"
        iface['wrongsizing'] = "Неправилен маркер за оразмеряване или метод"\
                               " за оразмеряване! Моля, опитайте други!"
        iface['closetab'] = "Затвори раздела"
        iface['loadpanel'] = "Зареди панела"
        iface['nopanel'] = "Не е зареден панел"
        iface['allele_col'] = "Алел"
        iface['loadpaneldlg'] = "Зареди файл с панела"
        iface['loadbinsdlg'] = "Изберете файл с бинове"
        iface['nobinsmsg'] = "Не е намерен или избран файл с бинове. "\
                             "За анотиране ще се използват диапазони на "\
                             "алелите — конкретни номера на алелите "\
                             "няма да бъдат налични."
        iface['loadstutterdlg'] = "Изберете файл с коефициенти на статер"
        iface['codisexport'] = "Експорт CODIS XML"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Импортиране на панела в библиотеката"
        iface['panelimported'] = "Панел(ите) е(са) запазен(и) в библиотеката."
        iface['codisdlgtitle'] = "Експорт CODIS 3.2 CMF"
        iface['codisdestori'] = "ORI получател:"
        iface['codissourcelab'] = "ID лаборатория-източник:"
        iface['codisanalyst'] = "ID потребител:"
        iface['codisbatch'] = "ID партида (незадълж.):"
        iface['codiskit'] = "Комплект (незадълж.):"
        iface['codisdt'] = "Дата/час на подаване:"
        iface['codisspecimens'] = "Образци:"
        iface['codisfile'] = "Файл"
        iface['codisspecimenid'] = "ID образец"
        iface['codiscategory'] = "Категория"
        iface['codisnopanel'] = "\u26a0 Някои раздели нямат заредена панел — "\
                                "данните за локуси ще липсват за тези образци."
        iface['codisnosize'] = "\u26a0 Някои раздели нямат пикове с размер — "\
                               "данните за локуси ще липсват за тези образци."
        iface['codisvalidation'] = "Моля, попълнете: ORI получател, ID "\
                                   "лаборатория, ID потребител и дата/час."
        iface['codisemptyid'] = "ID образец е празен за избран ред."
        iface['codisnorows'] = "Не са избрани образци за експорт."
        iface['codissave'] = "Запазване на CODIS XML"
        iface['menu_file'] = "Файл"
        iface['menu_settings'] = "Настройки"
        iface['menu_help'] = "Помощ"
        iface['addsizestd'] = "Добавяне на размерен стандарт"
        iface['stdname'] = "Име на стандарта:"
        iface['stdchannel'] = "ILS канал (ABIF ключ):"
        iface['stdsizes'] = "Размери (разделени с интервал):"
        iface['stdadded'] = "Размерният стандарт е добавен успешно"
    elif "de" in lang:
        iface['ch_inact_msg'] = "Inaktiver Kanal"
        iface['aboutbtn'] = "Über das Programm"
        iface['infoboxtxt'] = "FragalyseQt Version 0.5.3, Codename "\
                              "\"Southern\".\n\nDiese Programmversion "\
                              "unterstützt die gleichzeitige Analyse von bis "\
                              "zu 8 verschiedenen Fluoreszenzkanälen, "\
                              "selektives Ausblenden von Kanälen, "\
                              "nicht-lateinische Laufnamen, kann beschädigte "\
                              "Dateien korrekt verarbeiten, unterstützt den "\
                              "Export von Kanalnamen, Peak-Positionen, "\
                              "Flächen, Größen und FWHM-Werten im CSV-Format "\
                              "für jede *.FSA/*.HID-Datei sowie den Export "\
                              "interner Analysedaten für *.FSA/*.HID-Dateien "\
                              "von ABI 3500 und SeqStudio-Geräten. Außerdem "\
                              "wird das Lesen nativer Nanophore-05 .frf-"\
                              "Dateien unterstützt (hochgradig "\
                              "experimentell). Ab Version 0.5 wird "\
                              "Allel-Binning mittels GeneMapper-, GeneMarker-"\
                              " und NCBI-OSIRIS-LadderInfo-Panel-Dateien"\
                              " unterstützt. Wenn ein Panel mit"\
                              " Stutter-Verhältnis-Daten geladen wird"\
                              " (GeneMapper-Stutter-Dateien oder"\
                              " GeneMarker-Panels), wird die Filterung von"\
                              " Stutter-Peaks automatisch angewendet."\
                              " Hinweis: NCBI-OSIRIS-Panels enthalten keine"\
                              " Stutter-Verhältnis-Daten — die"\
                              " Stutter-Filterung ist für sie nicht verfügbar"\
                              ". Der Export im Format CODIS 3.2 CMF XML wird"\
                              " ebenfalls unterstützt (Ctrl+Shift+C):"\
                              " Proben auswählen, Kategorien und"\
                              " Labormetadaten zuweisen — FragalyseQt"\
                              " erstellt eine valide CODISImportFile-Datei"\
                              " zur Einreichung in die Datenbank."\
                              "\n\nPeak-Flächen werden unter der Annahme "\
                              "berechnet, dass es sich um Gaußsche Peaks "\
                              "handelt.\n\nLizenziert unter GNU AGPL "\
                              "Version 3.\n\nWenn Sie den Autor kontaktieren "\
                              "möchten, schreiben Sie bitte an "\
                              "dorif11@gmail.com"
        iface['openfragmentfile'] = "Datei öffnen"
        iface['exportinternal'] = "Interne Analysedaten exportieren"
        iface['csvexport'] = "Als CSV exportieren"
        iface['exportwholesession'] = "Gesamte Sitzung exportieren"
        iface['choosefolder'] = "Exportordner auswählen"
        iface['unsuppeq'] = "Nicht unterstütztes Gerät!"
        iface['unsuppeqmsg'] = "Interne Analysedaten können nur aus "\
                               "FSA-Dateien exportiert werden, die von "\
                               "ABI 3500 oder SeqStudio-Geräten erzeugt "\
                               "wurden!"
        iface['dmgdfile'] = "Beschädigte Datei!"
        iface['nodatamsg'] = "Die Datei enthält keine Daten!"
        iface['hidechannel'] = "Kanal ausblenden "
        iface['minph'] = "Minimale Peakhöhe auswählen:"
        iface['minpw'] = "Minimale Peakbreite auswählen:"
        iface['minpp'] = "Minimale Peakprominenz auswählen:"
        iface['minww'] = "Minimale Fensterbreite auswählen:"
        iface['minah'] = "Min. Allel-Höhe:"
        iface['menu_view'] = "Ansicht"
        iface['splitview'] = "Kanäle trennen"
        iface['savecsv'] = "CSV speichern"
        iface['bcd'] = "Basislinienkorrektur und Rauschunterdrückung."
        iface['processbatch'] = "Gesamten Stapel verarbeiten"
        iface['savesession'] = "Sitzung speichern"
        iface['opensession'] = "Sitzung öffnen"
        iface['savesessiontitle'] = "Sitzung speichern"
        iface['opensessiontitle'] = "Sitzung öffnen"
        iface['sessionnamelabel'] = "Sitzungsname:"
        iface['sessionverifytitle'] = "Dateiüberprüfung"
        iface['sessionverifymsg'] = ("Eine oder mehrere Quelldateien fehlen "
                                     "oder wurden geändert.\nDie Sitzung wird "
                                     "im Nur-Lese-Modus mit den in der Datenbank "
                                     "gespeicherten Daten geöffnet.")
        iface['openreadonly'] = "Nur lesend öffnen"
        iface['nosessions'] = "Keine gespeicherten Sitzungen gefunden."
        iface['readonlyplot'] = "Nur Lesen — Quelldatei nicht verfügbar"
        iface['wrongsizing'] = "Falsche Leiter oder Größenbestimmungs"\
                               "methode! Bitte versuchen Sie andere!"
        iface['closetab'] = "Registerkarte schließen"
        iface['loadpanel'] = "Panel laden"
        iface['nopanel'] = "Kein Panel geladen"
        iface['allele_col'] = "Allel"
        iface['loadpaneldlg'] = "Panel-Datei laden"
        iface['loadbinsdlg'] = "Bins-Datei auswählen"
        iface['nobinsmsg'] = "Keine Bins-Datei gefunden oder ausgewählt. "\
                             "Für die Annotation werden Allel-Bereiche "\
                             "verwendet — spezifische Allel-Nummern "\
                             "sind nicht verfügbar."
        iface['loadstutterdlg'] = "Stutter-Verhältnis-Datei auswählen"
        iface['codisexport'] = "CODIS XML exportieren"
        iface['soapapimenu'] = "SOAP API"
        iface['importpanel'] = "Panel in Bibliothek importieren"
        iface['panelimported'] = "Panel(s) in Bibliothek gespeichert."
        iface['codisdlgtitle'] = "CODIS 3.2 CMF Export"
        iface['codisdestori'] = "Ziel-ORI:"
        iface['codissourcelab'] = "Quell-Labor-ID:"
        iface['codisanalyst'] = "Benutzer-ID:"
        iface['codisbatch'] = "Chargen-ID (opt.):"
        iface['codiskit'] = "Kit (opt.):"
        iface['codisdt'] = "Einreichungsdatum/-zeit:"
        iface['codisspecimens'] = "Proben:"
        iface['codisfile'] = "Datei"
        iface['codisspecimenid'] = "Proben-ID"
        iface['codiscategory'] = "Kategorie"
        iface['codisnopanel'] = "\u26a0 Einige Tabs haben kein Panel — "\
                                "Locus-Daten fehlen für diese Proben."
        iface['codisnosize'] = "\u26a0 Einige Tabs haben keine dimensionierten"\
                               " Peaks — Locus-Daten fehlen für diese Proben."
        iface['codisvalidation'] = "Bitte ausfüllen: Ziel-ORI, Quell-Labor-ID"\
                                   ", Benutzer-ID und Datum/Uhrzeit."
        iface['codisemptyid'] = "Proben-ID ist leer für eine ausgewählte Zeile."
        iface['codisnorows'] = "Keine Proben für den Export ausgewählt."
        iface['codissave'] = "CODIS XML speichern"
        iface['menu_file'] = "Datei"
        iface['menu_settings'] = "Einstellungen"
        iface['menu_help'] = "Hilfe"
        iface['addsizestd'] = "Größenstandard hinzufügen"
        iface['stdname'] = "Standardname:"
        iface['stdchannel'] = "ILS-Kanal (ABIF-Schlüssel):"
        iface['stdsizes'] = "Größen (leerzeichengetrennt):"
        iface['stdadded'] = "Größenstandard erfolgreich hinzugefügt"
